import {tenantAuth,createKey} from '../auth.js';
import {PERMISSIONS,humanOnly,agentOnly,videoAccess,folderAccess,assertion} from '../access/policy.js';
import {fail,uid,now,text,integer,choice} from '../util.js';
export async function admin(c,tid){await tenantAuth(c,tid,'videos:write','admin');humanOnly(c);}
export async function listAgents(c,tid){await admin(c,tid);return c.db.all('SELECT * FROM agents WHERE tenant_id=? ORDER BY legacy,name',[tid]);}
export async function getAgent(c,tid,id){await admin(c,tid);const a=await c.db.one('SELECT * FROM agents WHERE id=? AND tenant_id=?',[id,tid]);if(!a)fail(404,'AGENT_NOT_FOUND');return {...a,grants:await c.db.all('SELECT * FROM agent_grants WHERE agent_id=?',[id]),keys:await c.db.all('SELECT id,label,created_at,expires_at,revoked_at FROM api_keys WHERE agent_id=?',[id]),usage:await c.db.all('SELECT * FROM agent_reservations WHERE agent_id=? ORDER BY created_at DESC LIMIT 100',[id]),activity:await c.db.all('SELECT a.* FROM audit_log a WHERE a.tenant_id=? AND (a.resource_id=? OR a.actor IN (SELECT \'key:\'||id FROM api_keys WHERE agent_id=?)) ORDER BY a.created_at DESC LIMIT 100',[tid,id,id])};}
export async function saveAgent(c,tid,b,id){await admin(c,tid);const old=id?await getAgent(c,tid,id):null;if(old)integer(b.expectedRevision,'expectedRevision',1);const perms=b.permissions??(old?JSON.parse(old.permissions_json):[]);if(!Array.isArray(perms)||perms.some(x=>!PERMISSIONS.includes(x)))fail(400,'INVALID_AGENT_PERMISSIONS');
 const name=text(b.name??old?.name,'name',80),purpose=text(b.purpose??old?.purpose??'','purpose',500,0),status=choice(b.status??old?.status??'active',['active','suspended'],'status');const limits=['operation_micros','run_micros','daily_micros','monthly_micros','concurrent_jobs','retained_bytes','upload_bytes_daily'];const values=limits.map(k=>integer(b[k]??old?.[k]??0,k,0,k==='concurrent_jobs'?100:1e15));
 id??=uid('ag_');const ops=old?assertion('EXISTS(SELECT 1 FROM agents WHERE id=? AND revision=?)',[id,b.expectedRevision]):[];
 if(old)ops.push([`UPDATE agents SET name=?,purpose=?,status=?,permissions_json=?,${limits.map(k=>k+'=?').join(',')},revision=revision+1 WHERE id=?`,[name,purpose,status,JSON.stringify([...new Set(perms)]),...values,id]]);
 else ops.push([`INSERT INTO agents(id,tenant_id,name,purpose,status,permissions_json,${limits.join(',')},created_by,created_at) VALUES(${Array(15).fill('?').join(',')})`,[id,tid,name,purpose,status,JSON.stringify([...new Set(perms)]),...values,c.actor.email,now()]]);
 await c.db.batch(ops);await c.db.audit(tid,c.actor.email,'agent.save',id);return getAgent(c,tid,id);
}
export async function setGrants(c,tid,id,b){const a=await getAgent(c,tid,id);integer(b.expectedRevision,'expectedRevision',1);if(!Array.isArray(b.grants)||b.grants.length>100)fail(400,'INVALID_GRANTS');const ops=[...assertion('EXISTS(SELECT 1 FROM agents WHERE id=? AND revision=?)',[id,b.expectedRevision]),['DELETE FROM agent_grants WHERE agent_id=?',[id]]];
 for(const g of b.grants){choice(g.resourceType,['video','folder','live'],'resourceType');const resource=await c.db.one(`SELECT id FROM ${{video:'videos',folder:'folders',live:'live_inputs'}[g.resourceType]} WHERE id=? AND tenant_id=?`,[g.resourceId,tid]);if(!resource)fail(400,'GRANT_RESOURCE_NOT_FOUND');ops.push(['INSERT INTO agent_grants(id,tenant_id,agent_id,resource_type,resource_id,access,inherit) VALUES(?,?,?,?,?,?,?)',[uid('gr_'),tid,id,g.resourceType,g.resourceId,choice(g.access,['read','write'],'access'),g.inherit===true?1:0]]);}
 ops.push(['UPDATE agents SET revision=revision+1 WHERE id=?',[id]]);await c.db.batch(ops);await c.db.audit(tid,c.actor.email,'agent.grants',id,{count:b.grants.length});return getAgent(c,tid,id);
}
export async function agentKey(c,tid,id,b){const a=await getAgent(c,tid,id);if(a.legacy)fail(409,'LEGACY_AGENT_REQUIRES_MIGRATION');return createKey(c,tid,{...b,agentId:id});}
export async function migrationReport(c,tid,b){await admin(c,tid);const keys=await c.db.all('SELECT k.id,k.label,k.scopes_json,k.agent_id FROM api_keys k LEFT JOIN agents a ON a.id=k.agent_id WHERE k.tenant_id=? AND k.revoked_at IS NULL AND k.expires_at>? AND (k.agent_id IS NULL OR a.legacy=1)',[tid,now()]);if(b?.activate){if(keys.length)fail(409,'LEGACY_KEYS_REMAIN','Revoke broad keys or explicitly constrain their named legacy principals first.');await c.db.run('UPDATE tenants SET agent_security_version=1 WHERE id=?',[tid]);await c.db.audit(tid,c.actor.email,'agent.security.activate',tid);}return {isolated:!keys.length,minimumSecurityVersion:1,legacyKeys:keys};}
export async function constrainLegacy(c,tid,id,b){const a=await getAgent(c,tid,id);if(!a.legacy||b.confirm!==true)fail(400,'LEGACY_MIGRATION_CONFIRMATION_REQUIRED');await c.db.batch([...assertion('EXISTS(SELECT 1 FROM agents WHERE id=? AND revision=?)',[id,integer(b.expectedRevision,'expectedRevision',1)]),['UPDATE agents SET legacy=0,revision=revision+1 WHERE id=?',[id]]]);await c.db.audit(tid,c.actor.email,'agent.legacy.constrain',id);return getAgent(c,tid,id);}
export async function self(c,tid){await tenantAuth(c,tid);if(!agentOnly(c))return {legacy:!!c.actor.legacy,message:'Use a named, scoped agent credential for isolated access.'};const a=await c.db.one('SELECT * FROM agents WHERE id=?',[c.actor.agentId]);return {...a,keyId:c.actor.keyId,grants:await c.db.all('SELECT * FROM agent_grants WHERE agent_id=?',[a.id]),usage:await c.db.all('SELECT * FROM agent_reservations WHERE agent_id=? ORDER BY created_at DESC LIMIT 100',[a.id]),upload:{method:'PUT',path:'/api/videos/{videoId}/parts/{partNumber}',status:'/api/videos/{videoId}/upload'},approvals:'Publishing, sharing and deletion require an exact human-approved request.'};}
export async function explain(c,tid,b){await tenantAuth(c,tid);try{if(b.videoId){const v=await c.db.one('SELECT * FROM videos WHERE id=? AND tenant_id=?',[b.videoId,tid]);if(!v)return {allowed:false,reason:'RESOURCE_NOT_ACCESSIBLE'};await videoAccess(c,v,b.access==='write'?'write':'read');}else await folderAccess(c,tid,b.folderId,b.access==='write'?'write':'read');return {allowed:true};}catch(e){if(e.status===403||e.status===404)return {allowed:false,reason:'RESOURCE_NOT_ACCESSIBLE'};throw e;}}
