import {requestResourceApproval,resourceApprovals,decideResourceApproval} from './resources.js';
import {lineage,lineageGuards,checkLineage,approvalLineage} from '../access/lineage.js';
import {tenantAuth} from '../auth.js';
import {requireVideo} from '../library.js';
import {agentOnly,permission,humanOnly,assertion,checkRevision,videoFilter} from '../access/policy.js';
import {fail,uid,now,text,integer,choice,canonicalJSON,hash} from '../util.js';
export function actionPayload(action,b){if(action==='delete')return {confirmDelete:true};if(action==='share')return {days:integer(b.days??7,'days',1,90)};return Object.fromEntries(['visibility','allowedOrigins','downloadsEnabled','watermarkText','maxSessions'].filter(k=>Object.hasOwn(b,k)).map(k=>[k,b[k]]));}
export async function requestApproval(c,tid,b){if(b.resourceType&&b.resourceType!=='video')return requestResourceApproval(c,tid,b);await tenantAuth(c,tid);if(!agentOnly(c))fail(403,'NAMED_AGENT_REQUIRED');const action=choice(b.action,['publish','share','delete'],'action');permission(c,action);const v=await requireVideo(c,b.videoId,'videos:write','editor');await checkRevision(c,v,b.expectedRevision);const payload=actionPayload(action,b.payload??{});if(action==='publish'&&!Object.keys(payload).length)fail(400,'EMPTY_PUBLICATION_REQUEST');const json=canonicalJSON(payload),id=uid('ap_'),inputs=await lineage(c,v.id);await c.db.run('INSERT INTO agent_approvals(id,tenant_id,agent_id,video_id,action,revision,payload_json,payload_hash,expires_at,created_at,inputs_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[id,tid,c.actor.agentId,v.id,action,v.revision,json,await hash(json),now()+integer(b.ttlSeconds??3600,'ttlSeconds',60,86400)*1000,now(),JSON.stringify(inputs)]);await c.db.audit(tid,c.actor.email,'approval.request',id,{action,videoId:v.id});return {id,state:'pending'};}
export async function listApprovals(c,tid){await tenantAuth(c,tid,'videos:read','viewer');const f=videoFilter(c);return [...await c.db.all(`SELECT p.*,a.name agent_name,v.title FROM agent_approvals p JOIN agents a ON a.id=p.agent_id JOIN videos v ON v.id=p.video_id WHERE p.tenant_id=? AND ${f.sql} ${c.actor.type==='key'?'AND p.agent_id=?':''} ORDER BY p.created_at DESC LIMIT 100`,[tid,...f.args,...(c.actor.type==='key'?[c.actor.agentId??'']:[])]),...await resourceApprovals(c,tid)].sort((a,b)=>b.created_at-a.created_at).slice(0,100);}
export async function decideApproval(c,tid,id,b){await tenantAuth(c,tid,'videos:write','admin');humanOnly(c);const decision=choice(b.decision,['approved','rejected'],'decision');const other=await c.db.one('SELECT * FROM resource_approvals WHERE id=? AND tenant_id=?',[id,tid]);if(other)return decideResourceApproval(c,tid,other,decision);const p=await c.db.one('SELECT * FROM agent_approvals WHERE id=? AND tenant_id=?',[id,tid]);if(!p)fail(404,'APPROVAL_NOT_FOUND');await approvalLineage(c,p.video_id,JSON.parse(p.inputs_json));const v=await requireVideo(c,p.video_id);if(p.expires_at<=now()||p.revision!==v.revision)fail(409,'APPROVAL_STALE');const r=await c.db.run("UPDATE agent_approvals SET state=?,decided_by=?,decided_at=? WHERE id=? AND state='pending' AND expires_at>? AND revision=(SELECT revision FROM videos WHERE id=video_id)",[decision,c.actor.email,now(),id,now()]);if(!r.meta.changes)fail(409,'APPROVAL_ALREADY_DECIDED');await c.db.audit(tid,c.actor.email,'approval.'+decision,id);return {id,state:decision};}
export async function approvalOps(c,v,action,b){if(!agentOnly(c))return [];permission(c,action);const id=text(b.approvalId,'approvalId',80),payloadHash=await hash(canonicalJSON(actionPayload(action,b)));const args=[id,c.actor.agentId,v.id,v.revision,action,payloadHash,now()];const condition="id=? AND agent_id=? AND video_id=? AND revision=? AND action=? AND payload_hash=? AND state='approved' AND expires_at>? AND revision=(SELECT revision FROM videos WHERE id=video_id)";
 const approval=await c.db.one('SELECT * FROM agent_approvals WHERE '+condition,args);if(!approval)fail(403,'HUMAN_APPROVAL_REQUIRED','A current approval for this exact action and resource version is required.');
 await approvalLineage(c,v.id,JSON.parse(approval.inputs_json));return [...lineageGuards(JSON.parse(approval.inputs_json),v.id),...assertion('EXISTS(SELECT 1 FROM agent_approvals WHERE '+condition+')',args),["UPDATE agent_approvals SET state='consumed',consumed_at=? WHERE id=?",[now(),id]]];
}
