import {bytesHash,partFingerprint} from './artifacts/fingerprint.js';
import {checkJobAccess,policyOps} from './access/policy.js';
import {verifyToken} from './crypto.js';
import {bodyBytes,fail,assetPath,integer,now,uid,parseRange} from './util.js';
import {reserveObject,putObject,getObject,PART_SIZE} from './storage.js';
export async function jobAuth(c,jid){const token=new URL(c.req.url).searchParams.get('token');const p=await verifyToken(token,c.env.SIGNING_SECRET,'job-io');if(p.jid!==jid)fail(403,'JOB_TOKEN_MISMATCH');const job=await c.db.one('SELECT * FROM jobs WHERE id=? AND tenant_id=?',[jid,p.tid]);if(!job||job.finished_at||['cancelled','cancelling','cleanup_required'].includes(job.state))fail(403,'JOB_NOT_ACTIVE');await checkJobAccess(c,job);c.meter.tenantId=job.tenant_id;c.meter.videoId=job.video_id;c.meter.category='job-io';return job;}
export async function sourceFile(c,job,vid,path){const payload=JSON.parse(job.payload_json),ids=payload.sourceVideoIds||[job.video_id];if(!ids.includes(vid))fail(403,'SOURCE_NOT_AUTHORISED');path=assetPath(path);const v=await c.db.one("SELECT * FROM videos WHERE id=? AND tenant_id=? AND status NOT IN ('deleting','deleted')",[vid,job.tenant_id]);if(!v||path!==v.source_path&&path!==v.caption_path)fail(403,'SOURCE_NOT_AUTHORISED');const o=await c.db.one("SELECT * FROM objects WHERE video_id=? AND path=? AND status='ready'",[vid,path]);if(!o)fail(404,'SOURCE_MISSING');const range=parseRange(c.req.headers.get('range'),o.size);const headers={'Content-Type':o.content_type,'Content-Length':String(range?.length??o.size),'Accept-Ranges':'bytes','Cache-Control':'no-store'};if(range)headers['Content-Range']=`bytes ${range.offset}-${range.end}/${o.size}`;if(c.req.method==='HEAD')return new Response(null,{headers,status:range?206:200});const file=await getObject(c,o.object_key,range?{range:{offset:range.offset,length:range.length}}:undefined);if(!file)fail(404,'SOURCE_MISSING');return new Response(file.body,{headers,status:range?206:200});}
function jobPath(job,path){path=assetPath(path);if(!path.startsWith(`jobs/${job.id}/`))fail(403,'OUTPUT_PREFIX_MISMATCH');return path;}
async function video(c,job){const v=await c.db.one('SELECT * FROM videos WHERE id=? AND tenant_id=?',[job.video_id,job.tenant_id]);if(!v)fail(404,'VIDEO_NOT_FOUND');return v;}
function role(req){const value=new URL(req.url).searchParams.get('role')||'playback';if(!['source','playback','caption','thumbnail','analysis','generated'].includes(value))fail(400,'INVALID_ROLE');return value;}
export async function internalAsset(c,job,path){path=jobPath(job,path);const data=await bodyBytes(c.req,PART_SIZE);return putObject(c,await video(c,job),path,data,role(c.req));}
export async function internalUploadCreate(c,job,b){const path=jobPath(job,b.path),size=integer(b.size,'size',1,Number(c.env.MAX_OUTPUT_BYTES||3221225472));const v=await video(c,job),o=await reserveObject(c,v,path,size,b.role||'playback');const existing=await c.db.one('SELECT * FROM job_uploads WHERE job_id=? AND object_id=?',[job.id,o.id]);if(existing)return {id:existing.id,partSize:PART_SIZE,completed:!!existing.completed_at};c.meter.add('r2_a');const mp=await c.env.VIDEOS.createMultipartUpload(o.object_key,{httpMetadata:{contentType:o.content_type}}),upid=uid('ju_');await c.db.run('INSERT INTO job_uploads(id,job_id,object_id,multipart_id,size,created_at) VALUES(?,?,?,?,?,?)',[upid,job.id,o.id,mp.uploadId,size,now()]);return {id:upid,partSize:PART_SIZE};}
export async function internalUploadPart(c,job,upid,n){const u=await c.db.one('SELECT j.*,o.object_key FROM job_uploads j JOIN objects o ON o.id=j.object_id WHERE j.id=? AND j.job_id=?',[upid,job.id]);if(!u||u.completed_at)fail(409,'UPLOAD_NOT_ACTIVE');n=integer(Number(n),'partNumber',1,Math.ceil(u.size/PART_SIZE));const bytes=await bodyBytes(c.req,PART_SIZE);if(bytes.length!==Math.min(PART_SIZE,u.size-(n-1)*PART_SIZE))fail(400,'PART_SIZE_MISMATCH');c.meter.add('r2_a');const p=await c.env.VIDEOS.resumeMultipartUpload(u.object_key,u.multipart_id).uploadPart(n,bytes);await c.db.run('INSERT INTO job_upload_parts(upload_id,part_number,etag,size,created_at,sha256) VALUES(?,?,?,?,?,?) ON CONFLICT(upload_id,part_number) DO UPDATE SET etag=excluded.etag,sha256=excluded.sha256',[upid,n,p.etag,bytes.length,now(),await bytesHash(bytes)]);return {partNumber:n,etag:p.etag};}
export async function internalUploadComplete(c,job,upid){const u=await c.db.one('SELECT j.*,o.object_key FROM job_uploads j JOIN objects o ON o.id=j.object_id WHERE j.id=? AND j.job_id=?',[upid,job.id]);if(!u)fail(404,'UPLOAD_NOT_FOUND');if(u.completed_at)return {ok:true};const parts=await c.db.all('SELECT * FROM job_upload_parts WHERE upload_id=? ORDER BY part_number',[upid]);if(parts.length!==Math.ceil(u.size/PART_SIZE)||parts.reduce((a,p)=>a+p.size,0)!==u.size)fail(409,'UPLOAD_INCOMPLETE');let o;try{c.meter.add('r2_a');o=await c.env.VIDEOS.resumeMultipartUpload(u.object_key,u.multipart_id).complete(parts.map(p=>({partNumber:p.part_number,etag:p.etag})));}catch(e){c.meter.add('r2_b');o=await c.env.VIDEOS.head(u.object_key);if(!o||o.size!==u.size)throw e;}const fingerprint=await partFingerprint(parts,u.size);await c.db.batch([...policyOps(c),["UPDATE objects SET status='ready',stored_at=COALESCE(stored_at,?),etag=?,content_hash=? WHERE id=?",[now(),o.etag,fingerprint?'parts:'+fingerprint:null,u.object_id]],['UPDATE job_uploads SET completed_at=? WHERE id=?',[now(),upid]]]);return {ok:true};}
