import {dispatchContainer} from './processing/container-dispatch.js';
import {resultManifestOps} from './artifacts/job-results.js';
import {jobVersionOps,checkSourceVersions} from './evidence/versions.js';
import {summaryPrompt,renderSummary,summaryFormat} from './ai/summary.js';
import {readProgress,recordProgress,indexProgress} from './processing/progress.js';
import {runJob} from './runs/job-contract.js';
import {processorFailure,safeDiagnostics,startupDiagnostics} from './processing/diagnostics.js';
import {visibleJob} from './access/results.js';
import {agentOnly,permission,videoFilter,videoAccess,folderAccess,checkJobAccess,checkRevision,revisionOps,policyOps,assertion} from './access/policy.js';
import {approvalOps} from './approvals/service.js';
import {reserveAgent,settleAgent} from './budgets/reservations.js';
import {claimOps} from './runs/claims.js';
import {chatOptions} from './ai/chat-options.js';
import {mediaJobOptions,prepareMediaSources,finishMediaJob,mediaResultOps,ENCODING_PROFILES} from './media-features.js';
import {tenantAuth} from './auth.js';
import {requireVideo,verifyFolder} from './library.js';
import {deleteObjects,getObject,putObject} from './storage.js';
import {aiReady,processIndexUnit,finishIndex,semanticSearch,answerQuestion,generateText,generateAsset,embed,indexArtifact,record} from './intelligence.js';
import {streamStep,streamCleanup,streamImportStep} from './stream.js';
import {signToken,unseal} from './crypto.js';
import {costEvent} from './meter.js';
import {RATES,MARKUP,STORAGE_MARKUP,customerCostUsd} from './rates.js';
import {fail,uid,now,text,integer,number,choice,allowedExternal,enc,hash,canonicalJSON} from './util.js';
export const JOB_KINDS=['probe','transcode','preview','export','index','render','capture','stream','stream_import','semantic_search','ask','summarize','embed_artifacts','generate_image','generate_speech','delete'];
const CONTAINER_KINDS=new Set(['probe','transcode','preview','export','index','render','capture','stream','stream_import']);
const NEW_ASSET_KINDS=new Set(['render','capture','stream_import','generate_image','generate_speech']);
export function jobView(j){const {payload_json,result_json,progress_json,...safe}=j;let result;try{result=JSON.parse(result_json||'null');}catch{result=null;}return {...safe,result,progress:readProgress(j)};}
export async function quoteJob(c,tid,b){const kind=choice(b.kind,JOB_KINDS,'kind'),scope=kind==='delete'?'videos:write':'processing:write';await tenantAuth(c,tid,scope,'editor');chatOptions(b);const wall=integer(b.maxWallSeconds??900,'maxWallSeconds',30,3600);let duration=number(b.durationSeconds??0,'durationSeconds',0,14400),size=0;if(b.videoId){const v=await requireVideo(c,b.videoId,scope,'editor');if(v.tenant_id!==tid)fail(403,'TENANT_MISMATCH');duration=Math.max(duration,v.duration_seconds);size=v.expected_bytes;}
 if(kind==='stream_import'){const r=await c.db.one('SELECT duration_seconds FROM live_recordings WHERE provider_uid=? AND tenant_id=? AND deleted_at IS NULL',[b.recordingId,tid]);if(!r)fail(404,'RECORDING_NOT_FOUND');duration=Math.max(duration,r.duration_seconds);}
 // An authorization hold, not a promise of final provider cost. Hard execution/output limits enforce this envelope.
 let supplier=CONTAINER_KINDS.has(kind)?wall*(.000020+6*.0000025+12*.00000007)+.02:0;
 if(['transcode','preview','export','render','capture','stream','stream_import'].includes(kind))supplier+=.15; // output-transfer reserve (3 GB at conservative region price)
 if(kind==='index')supplier+=duration/60*.00051+60*.00065+.03;
 if(['stream','stream_import'].includes(kind))supplier+=Math.max(duration,3600)/60*.001;
 if(['ask','summarize'].includes(kind))supplier+=.03;if(kind==='semantic_search'||kind==='embed_artifacts')supplier+=.03;
 if(kind==='generate_image')supplier+=.01;
 if(kind==='generate_speech')supplier+=Array.from(text(b.prompt,'prompt',1500)).length*.03/1000+.005;
 if(kind==='delete')supplier=0;
 return {kind,profile:mediaJobOptions(b).profile,renditionHeights:mediaJobOptions(b).heights,maxWallSeconds:wall,sourceBytes:size,durationSeconds:duration,reserveMicros:Math.ceil((supplier*MARKUP-(CONTAINER_KINDS.has(kind)?wall*12*.00000007*(MARKUP-STORAGE_MARKUP):0))*1e6),supplierEnvelopeMicros:Math.ceil(supplier*1e6),markup:MARKUP,quality:'conservative_credit_hold_not_invoice',note:'We reserve credits before starting and return the unused amount. Storage and ongoing hosting are billed separately.'};}
export async function createJob(c,tid,b,dispatchGuard=null){const kind=choice(b.kind,JOB_KINDS,'kind');await tenantAuth(c,tid,kind==='delete'?'videos:write':'processing:write','editor');const key=text(b.requestKey,'requestKey',160);const requestHash=await hash(canonicalJSON(b));const existing=await c.db.one('SELECT * FROM jobs WHERE tenant_id=? AND request_key=?',[tid,key]);if(existing){if(agentOnly(c)&&existing.agent_id!==c.actor.agentId)fail(409,'IDEMPOTENCY_KEY_UNAVAILABLE');await requireVideo(c,existing.video_id);if(existing.request_hash&&existing.request_hash!==requestHash)fail(409,'IDEMPOTENCY_PAYLOAD_MISMATCH');if(existing.kind!==kind||(b.videoId&&existing.video_id!==b.videoId))fail(409,'IDEMPOTENCY_KEY_REUSED');await visibleJob(c,existing);return jobView(existing);}
 if(b.keepSource===false)fail(400,'SOURCE_RETENTION_REQUIRED','This build retains originals for indexing and re-editing. Delete the asset to reclaim it.');
 if(kind==='delete'&&b.confirmDelete!==true)fail(400,'DELETE_CONFIRMATION_REQUIRED');
 if(CONTAINER_KINDS.has(kind)&&!c.env.MEDIA)fail(503,'CONTAINERS_NOT_ENABLED');if(['index','semantic_search','ask','summarize','embed_artifacts','generate_image','generate_speech'].includes(kind))aiReady(c,kind==='ask'||kind==='summarize'||kind==='index'&&b.visual!==false);
 if(['stream','stream_import'].includes(kind)&&c.env.STREAM_ENABLED!=='true')fail(503,'STREAM_NOT_ENABLED');if(['stream','stream_import'].includes(kind)&&!JSON.parse(c.tenant.provider_policy_json).allowStream)fail(403,'STREAM_NOT_ALLOWED_BY_POLICY');
 const quote=await quoteJob(c,tid,b);if(quote.reserveMicros>JSON.parse(c.tenant.provider_policy_json).maxJobMicros)fail(403,'POLICY_JOB_BUDGET_EXCEEDED');const budget=kind==='delete'?0:integer(b.budgetMicros,'budgetMicros',quote.reserveMicros,1e10);let v,p={visual:b.visual!==false,audio:b.audio!==false,visualPrompt:b.visualPrompt?text(b.visualPrompt,'visualPrompt',1000):'',encrypted:b.encrypted!==false,query:b.query?text(b.query,'query',1000):'',prompt:b.prompt?text(b.prompt,'prompt',kind==='generate_speech'?1500:4000):'',steps:b.steps??4,limit:b.limit??20,folderId:b.folderId??null,tag:b.tag??null,layer:b.layer??null};
 Object.assign(p,chatOptions(b));p.retrievalMode=choice(b.retrievalMode||'semantic',['semantic','hybrid'],'retrievalMode');if(b.sourceVersionId)p.sourceVersionId=text(b.sourceVersionId,'sourceVersionId',100);if(b.startSeconds!==undefined)p.startSeconds=number(b.startSeconds,'startSeconds',0,86400);if(b.endSeconds!==undefined)p.endSeconds=number(b.endSeconds,'endSeconds',0,86400);
 p={...p,...mediaJobOptions(b)};if(b.audioChunkSeconds!==undefined)p.audioChunkSeconds=choice(b.audioChunkSeconds,[30,60],'audioChunkSeconds');if(b.visualIntervalSeconds!==undefined)p.visualIntervalSeconds=integer(b.visualIntervalSeconds,'visualIntervalSeconds',10,300);
 if(NEW_ASSET_KINDS.has(kind)){
  await tenantAuth(c,tid,'videos:write','editor');const folder=await verifyFolder(c,tid,b.folderId??null);await folderAccess(c,tid,folder,'write');
  if(kind==='stream_import'){const r=await c.db.one('SELECT * FROM live_recordings WHERE provider_uid=? AND live_id=? AND tenant_id=? AND deleted_at IS NULL',[text(b.recordingId,'recordingId',32),text(b.liveId,'liveId',80),tid]);if(!r||!r.ready)fail(404,'RECORDING_NOT_READY');await tenantAuth(c,tid,'live:write','admin');p.recordingId=r.provider_uid;p.liveId=r.live_id;p.sourceVideoIds=[];}
  if(kind==='render'){const tl=await c.db.one('SELECT * FROM timelines WHERE id=? AND tenant_id=?',[b.timelineId,tid]);if(!tl)fail(404,'TIMELINE_NOT_FOUND');if(b.expectedTimelineRevision!==undefined&&tl.revision!==b.expectedTimelineRevision)fail(409,'TIMELINE_REVISION_CONFLICT');if(b.timelineSnapshot&&canonicalJSON(JSON.parse(tl.spec_json))!==canonicalJSON(b.timelineSnapshot))fail(409,'TIMELINE_REVISION_CONFLICT');p.timelineRevision={id:tl.id,revision:tl.revision};p.timeline=JSON.parse(tl.spec_json);p.sourceVideoIds=[...new Set(p.timeline.clips.map(x=>x.videoId))];for(const vid of p.sourceVideoIds){const src=await requireVideo(c,vid);if(src.tenant_id!==tid)fail(403,'TENANT_MISMATCH');}}
  if(kind==='capture'){await tenantAuth(c,tid,'sources:write','editor');const source=await c.db.one('SELECT * FROM sources WHERE id=? AND tenant_id=?',[b.sourceId,tid]);if(!source)fail(404,'SOURCE_NOT_FOUND');p.sourceId=source.id;p.captureSeconds=integer(b.captureSeconds??60,'captureSeconds',5,600);}
  const vid=uid('v_');v={id:vid,tenant_id:tid,title:text(b.title||kind.replaceAll('_',' '),'title',180),kind:kind==='generate_image'?'image':kind==='generate_speech'?'audio':'mp4',source_path:'source.mp4',primary_path:'source.mp4'};p.newVideo={folder,title:v.title,kind:v.kind};
 }else{v=await requireVideo(c,b.videoId,kind==='delete'?'videos:write':'processing:write','editor');if(v.tenant_id!==tid)fail(403,'TENANT_MISMATCH');if(kind!=='delete'&&!['ready','processing'].includes(v.status))fail(409,'VIDEO_NOT_READY');if(CONTAINER_KINDS.has(kind)&&v.source_path.endsWith('.m3u8'))fail(400,'ORIGINAL_SOURCE_REQUIRED','Upload a source MP4/WebM/MOV to use FFmpeg processing. Prepackaged HLS remains directly playable.');if(v.expected_bytes>Number(c.env.MAX_PROCESS_SOURCE_BYTES||3221225472)&&kind!=='delete')fail(413,'SOURCE_EXCEEDS_PROCESSING_LIMIT');}
 if(CONTAINER_KINDS.has(kind)&&!NEW_ASSET_KINDS.has(kind))await prepareMediaSources(c,v,kind,p);
 await runJob(c,tid,b,v,p);if(await c.db.one('SELECT id FROM jobs WHERE video_id=? AND finished_at IS NULL',[v.id]))fail(409,'VIDEO_HAS_ACTIVE_JOB','Cancel or finish the existing job first.');
 if(agentOnly(c)){permission(c,kind==='delete'?'delete':'process');if(!p.newVideo){await videoAccess(c,v,'write');await checkRevision(c,v,b.expectedRevision);}}
 if(agentOnly(c)){p.agentInputVersions=[];for(const id of p.sourceVideoIds||[]){const src=await requireVideo(c,id);p.agentInputVersions.push({videoId:id,revision:src.revision});}if(!p.newVideo&&v.visibility!=='private'&&!['ask','semantic_search','probe','export'].includes(kind)&&kind!=='delete')fail(403,'PUBLISHED_ASSET_REQUIRES_PRIVATE_DRAFT','Create a private working copy or have a human withdraw publication before replacing content.');}
 const jid=uid('j_'),ops=[...policyOps(c),...(p.newVideo?[]:[...revisionOps(c,'videos',v,b.expectedRevision),...claimOps(c,v.id,b)]),...(kind==='delete'?await approvalOps(c,v,'delete',b):[])];if(p.newVideo)ops.push(['INSERT INTO videos(id,tenant_id,folder_id,title,kind,status,primary_path,source_path,created_at,updated_at,agent_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[v.id,tid,p.newVideo.folder,v.title,v.kind,'processing',v.primary_path,v.source_path,now(),now(),agentOnly(c)?c.actor.agentId:null]]);
 ops.push(['INSERT INTO jobs(id,tenant_id,video_id,kind,next_run_at,created_at,updated_at,hold_micros,max_wall_seconds,keep_source,payload_json,request_key,agent_id,key_id,run_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[jid,tid,v.id,kind,now(),now(),now(),quote.reserveMicros,quote.maxWallSeconds,b.keepSource===false?0:1,JSON.stringify(p),key,c.actor.agentId??null,c.actor.keyId??null,b.runId??null]]);ops.push(...reserveAgent(c,jid,tid,quote.reserveMicros,b.runId));if(kind!=='delete')ops.push(...await jobVersionOps(c,jid,p.sourceVideoIds||(p.newVideo?[]:[v.id])));
 for(const sourceId of p.sourceVideoIds||[])if(sourceId!==v.id)ops.push(['INSERT INTO video_dependencies(video_id,source_video_id) VALUES(?,?) ON CONFLICT DO NOTHING',[v.id,sourceId]]);
 if(kind==='stream_import')ops.push(['UPDATE live_recordings SET local_video_id=?,import_job_id=? WHERE provider_uid=? AND tenant_id=?',[v.id,jid,p.recordingId,tid]]);
 if(quote.reserveMicros)ops.push(['INSERT INTO wallet_ledger(id,tenant_id,delta_micros,kind,reference,note,created_at) VALUES(?,?,?,?,?,?,?)',[uid('w_'),tid,-quote.reserveMicros,'reserve',`job:${jid}`,'Processing authorization hold, not revenue',now()]]);
 ops.push([kind==='delete'?"UPDATE videos SET status='deleting',token_version=token_version+1,updated_at=? WHERE id=?":"UPDATE videos SET status='processing',updated_at=? WHERE id=?",[now(),v.id]]);ops.push(['UPDATE jobs SET request_hash=? WHERE id=?',[requestHash,jid]]);if(p.timelineRevision)ops.push(...assertion('EXISTS(SELECT 1 FROM timelines WHERE id=? AND revision=?)',[p.timelineRevision.id,p.timelineRevision.revision]));if(dispatchGuard)ops.push(...dispatchGuard(jid));await c.db.batch(ops);await c.db.audit(tid,c.actor.email,'job.create',jid,{kind,videoId:v.id,approvedBudgetMicros:budget,heldMicros:quote.reserveMicros});await enqueue(c,jid);return jobView(await c.db.one('SELECT * FROM jobs WHERE id=?',[jid]));
}
export async function enqueue(c,jid,delay=0){if(!c.env.JOBS)return;try{c.meter.add('queues_ops');await c.env.JOBS.send({jobId:jid},{delaySeconds:Math.min(43200,Math.max(0,Math.ceil(delay)))});}catch{/* Durable D1 outbox is recovered by cron. */}}
export async function jobList(c,tid){await tenantAuth(c,tid,'videos:read','viewer');const f=videoFilter(c);const rows=await c.db.all(`SELECT j.*,v.title FROM jobs j JOIN videos v ON v.id=j.video_id WHERE j.tenant_id=? AND ${f.sql} ${agentOnly(c)?'AND j.agent_id=?':''} ORDER BY j.created_at DESC LIMIT 100`,[tid,...f.args,...(agentOnly(c)?[c.actor.agentId]:[])]);const out=[];for(const j of rows){try{out.push(jobView(await visibleJob(c,j)));}catch(e){if(e.status!==404)throw e;}}return out;}
export async function getJob(c,jid){const j=await c.db.one('SELECT * FROM jobs WHERE id=?',[jid]);if(!j)fail(404,'JOB_NOT_FOUND');await tenantAuth(c,j.tenant_id,'videos:read','viewer');await videoAccess(c,{id:j.video_id});if(agentOnly(c)&&j.agent_id!==c.actor.agentId)fail(404,'JOB_NOT_FOUND');await visibleJob(c,j);return {...jobView(j),events:await c.db.all('SELECT state,detail,created_at FROM job_events WHERE job_id=? ORDER BY created_at',[jid]),costs:await c.db.all('SELECT metric,quantity,unit_usd,quality,created_at FROM cost_events WHERE job_id=? ORDER BY created_at',[jid])};}
export async function cancelJob(c,jid){const j=await c.db.one('SELECT * FROM jobs WHERE id=?',[jid]);if(!j)fail(404,'JOB_NOT_FOUND');await requireVideo(c,j.video_id,'processing:write','editor');permission(c,'cancel');if(agentOnly(c)&&j.agent_id!==c.actor.agentId)fail(403,'JOB_OWNER_REQUIRED');if(j.finished_at)return jobView(j);if(j.kind==='delete')fail(409,'DELETE_CANNOT_BE_CANCELLED');await c.db.run("UPDATE jobs SET state='cancelling',next_run_at=?,updated_at=? WHERE id=?",[now(),now(),jid]);if(c.env.MEDIA){try{await c.env.MEDIA.get(c.env.MEDIA.idFromName(jid)).fetch('http://container/cancel',{method:'POST'});}catch{}}
 await c.db.audit(j.tenant_id,c.actor.email,'job.cancel',jid);await enqueue(c,jid);return {id:jid,state:'cancelling'};}
async function event(c,j,state,detail){await c.db.run('INSERT INTO job_events(id,job_id,tenant_id,state,detail,created_at) VALUES(?,?,?,?,?,?)',[uid('je_'),j.id,j.tenant_id,state,detail,now()]);}
async function finish(c,j,state,result={},error=null){
 const fresh=await c.db.one('SELECT * FROM jobs WHERE id=?',[j.id]);if(fresh.finished_at)return;if(state==='succeeded'&&j.kind!=='delete'){await checkJobAccess(c,j);await checkSourceVersions(c,j);}
 // Stop and clean paid provider resources before declaring completion. Cron retries failed cleanup.
 if(fresh.stream_uid&&!fresh.stream_deleted_at)await streamCleanup(c,fresh);
 const cost=await c.db.all('SELECT metric,quantity,unit_usd FROM cost_events WHERE job_id=?',[j.id]);const charged=Math.min(fresh.hold_micros,Math.round(customerCostUsd(cost)*1e6));const ops=[...assertion('EXISTS(SELECT 1 FROM jobs WHERE id=? AND finished_at IS NULL)',[j.id]),...(state==='succeeded'?policyOps(c):[]),...settleAgent(fresh,charged)];
 if(fresh.hold_micros){ops.push(['INSERT INTO wallet_ledger(id,tenant_id,delta_micros,kind,reference,note,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(tenant_id,kind,reference) DO NOTHING',[uid('w_'),j.tenant_id,fresh.hold_micros,'release',`job:${j.id}`,'Release processing authorization',now()]]);if(charged)ops.push(['INSERT INTO wallet_ledger(id,tenant_id,delta_micros,kind,reference,note,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(tenant_id,kind,reference) DO NOTHING',[uid('w_'),j.tenant_id,-charged,'charge',`job:${j.id}`,'Processing usage charge, capped to approved credit hold',now()]]);}
 if(state==='succeeded'&&j.kind!=='delete')ops.push(...await resultManifestOps(c,j,result));
 ops.push(['UPDATE jobs SET state=?,finished_at=?,updated_at=?,lease_until=0,last_error=?,result_json=? WHERE id=? AND finished_at IS NULL',[state,now(),now(),error,JSON.stringify({...result,provisionalTenantChargeMicros:charged,unobservedCostAtInvoice:true}),j.id]]);
 if(j.kind!=='delete'){const v=await c.db.one('SELECT * FROM videos WHERE id=?',[j.video_id]);const primary=result.primaryPath||v.primary_path,source=result.sourcePath||v.source_path;const ready=await c.db.one("SELECT id FROM objects WHERE video_id=? AND path=? AND status='ready'",[v.id,primary]);ops.push(['UPDATE videos SET status=?,primary_path=?,source_path=?,kind=?,duration_seconds=?,width=?,height=?,encrypted=?,thumbnail_path=COALESCE(?,thumbnail_path),updated_at=?,last_error=? WHERE id=?',[ready?'ready':'failed',primary,source,result.kind||v.kind,result.durationSeconds??v.duration_seconds,result.width??v.width,result.height??v.height,result.encrypted===undefined?v.encrypted:result.encrypted?1:0,result.thumbnailPath||null,now(),error,v.id]]);}
 if(state==='succeeded'){if(j.kind!=='delete')ops.push(['UPDATE videos SET revision=revision+1 WHERE id=?',[j.video_id]]);ops.push(...mediaResultOps(j,result));}await c.db.batch(ops);await event(c,j,state,error||'Job completed; processing hold reconciled.');
}
async function saveState(c,j,state,payload,result){await c.db.run('UPDATE jobs SET state=?,payload_json=COALESCE(?,payload_json),result_json=COALESCE(?,result_json),next_run_at=?,lease_until=0,updated_at=? WHERE id=? AND finished_at IS NULL AND state!=?', [state,payload?JSON.stringify(payload):null,result?JSON.stringify(result):null,now()+15000,now(),j.id,'cancelling']);await enqueue(c,j.id,15);}
async function containerInput(c,j,v,p){const token=await signToken({scope:'job-io',jid:j.id,tid:j.tenant_id},c.env.SIGNING_SECRET,Math.min(43200,j.max_wall_seconds+7200));const ids=p.sourceVideoIds||[v.id],sources=[];for(const vid of ids){const src=await c.db.one('SELECT * FROM videos WHERE id=? AND tenant_id=?',[vid,j.tenant_id]);if(!src)fail(409,'SOURCE_REMOVED');sources.push({id:vid,path:src.source_path,url:`${c.env.APP_ORIGIN}/source/${j.id}/${vid}/${src.source_path}?token=${encodeURIComponent(token)}`});}
 const input={id:j.id,kind:j.kind,videoId:v.id,baseUrl:c.env.APP_ORIGIN,token,maxWallSeconds:j.max_wall_seconds,maxSourceBytes:Number(c.env.MAX_PROCESS_SOURCE_BYTES||3221225472),maxOutputBytes:Number(c.env.MAX_OUTPUT_BYTES||3221225472),sources,payload:{...p}};
 if(j.kind==='capture'){const s=await c.db.one('SELECT * FROM sources WHERE id=? AND tenant_id=?',[p.sourceId,j.tenant_id]);if(!s)fail(404,'SOURCE_REMOVED');const url=await unseal(s.url_ciphertext,c.env.ENCRYPTION_SECRET||c.env.SIGNING_SECRET);allowedExternal(url,c.env);input.payload.captureUrl=url;input.sources=[];}
 if(['stream','stream_import'].includes(j.kind)&&p.streamExport){input.kind='import';input.sources=[];input.payload.downloadUrl=await unseal(p.downloadCipher,c.env.ENCRYPTION_SECRET||c.env.SIGNING_SECRET);}
 delete input.payload.downloadCipher;delete input.payload.newVideo;return input;
}
async function recordContainer(c,j,result){const observedWall=Number.isFinite(result.lifecycleSeconds)?result.lifecycleSeconds:Number.isFinite(result.wallSeconds)?result.wallSeconds:j.max_wall_seconds;const wall=Math.max(0,Math.min(observedWall,j.max_wall_seconds+120));const cpu=Number.isFinite(result.cpuSeconds)?result.cpuSeconds:wall;for(const [metric,q,quality]of [['container_cpu_seconds',cpu,Number.isFinite(result.cpuSeconds)?'process_rusage_not_provider_vcpu':'estimated_at_walltime'],['container_memory_gib_seconds',wall*6,'lifecycle_estimate_provisioned_6GiB'],['container_disk_gb_seconds',wall*12,'lifecycle_estimate_provisioned_12GB'],['container_egress_gb',(result.uploadedBytes||0)/1e9,'measured_output_bytes_region_estimated']])await costEvent(c,{id:`${j.id}:${metric}`,jobId:j.id,metric,quantity:q,unitUsd:RATES[metric].usd,quality});}
export async function stepJob(c,jid){let j=await c.db.one('SELECT * FROM jobs WHERE id=?',[jid]);if(!j||j.finished_at)return;c.meter.tenantId=j.tenant_id;c.meter.category='job';const locked=await c.db.run('UPDATE jobs SET lease_until=?,attempts=attempts+1 WHERE id=? AND lease_until<? AND finished_at IS NULL',[now()+180000,jid,now()]);if(!locked.meta.changes)return;let phase='job_access';
 try{j=await c.db.one('SELECT * FROM jobs WHERE id=?',[jid]);const v=await c.db.one('SELECT * FROM videos WHERE id=?',[j.video_id]);const tenant=await c.db.one('SELECT status FROM tenants WHERE id=?',[j.tenant_id]);let p=JSON.parse(j.payload_json),r=JSON.parse(j.result_json||'{}');
 if(j.state==='cleanup_required'){await finish(c,j,'failed',{},j.last_error||'CLEANUP_REQUIRED');return;}
 if(j.state==='cancelling'||tenant?.status!=='active'){if(c.env.MEDIA&&CONTAINER_KINDS.has(j.kind)){const stub=c.env.MEDIA.get(c.env.MEDIA.idFromName(j.id));try{await stub.fetch('http://container/cancel',{method:'POST'});await recordContainer(c,j,{wallSeconds:(now()-j.created_at)/1000});}catch{}}await finish(c,j,'cancelled',{},'Cancelled; completed provider work may still be billed.');return;}
 await checkJobAccess(c,j);phase='source_validation';if(j.kind!=='delete')await checkSourceVersions(c,j);
 if(now()-j.created_at>24*3600000)fail(504,'JOB_DEADLINE_EXCEEDED');
 if(j.kind==='delete'){
  if(v.upload_id){try{await c.env.VIDEOS.resumeMultipartUpload(v.upload_key,v.upload_id).abort();}catch{}await c.db.run('UPDATE upload_parts SET retired_at=COALESCE(retired_at,?) WHERE video_id=?',[now(),v.id]);}
  const uploads=await c.db.all('SELECT u.*,o.object_key FROM job_uploads u JOIN objects o ON o.id=u.object_id JOIN jobs j ON j.id=u.job_id WHERE j.video_id=? AND u.completed_at IS NULL',[v.id]);for(const u of uploads){try{await c.env.VIDEOS.resumeMultipartUpload(u.object_key,u.multipart_id).abort();}catch{}await c.db.run('UPDATE job_uploads SET completed_at=? WHERE id=?',[now(),u.id]);}
  if(!await deleteObjects(c,v)){await saveState(c,j,'deleting');return;}const artifacts=await c.db.all('SELECT id,vector_id FROM artifacts WHERE video_id=? LIMIT 100',[v.id]);if(artifacts.length){const ids=artifacts.filter(a=>a.vector_id).map(a=>a.vector_id);if(ids.length&&c.env.VECTORS)await c.env.VECTORS.deleteByIds(ids);await c.db.batch(artifacts.flatMap(a=>[['DELETE FROM detections WHERE artifact_id=?',[a.id]],['DELETE FROM artifacts WHERE id=?',[a.id]]]));await saveState(c,j,'deleting');return;}
  await c.db.run("DELETE FROM artifact_manifests WHERE video_id=?",[v.id]);await c.db.run("DELETE FROM processing_effects WHERE job_id IN (SELECT id FROM jobs WHERE video_id=?)",[v.id]);await c.db.run("UPDATE videos SET status='deleted',deleted_at=?,updated_at=? WHERE id=?",[now(),now(),v.id]);await finish(c,j,'succeeded',{deleted:true});return;
 }
 if(j.kind==='stream_import'&&!p.streamExport){const progress=await streamImportStep(c,j,p);await saveState(c,j,progress.state,progress.payload);return;}
 if(j.kind==='stream'&&!p.streamExport){const progress=await streamStep(c,j,v,p);await saveState(c,j,progress.state,progress.payload);return;}
 if(j.state==='ai_index'){
  await indexProgress(c,j,r.index||0,r.manifest.units?.length||0);const next=await processIndexUnit(c,j,v,r);await indexProgress(c,j,next.index,r.manifest.units?.length||0);if(!next.done){await saveState(c,j,'ai_index',null,next);return;}const result=await finishIndex(c,j,v);await finish(c,j,'succeeded',{...r.manifest,...result,reusedUnits:next.reusedUnits||0});return;
 }
 if(CONTAINER_KINDS.has(j.kind)){
  phase='container_binding';const stub=c.env.MEDIA.get(c.env.MEDIA.idFromName(j.id));
  if(j.state!=='container_running'){
   phase='container_input';const input=await containerInput(c,j,v,p);if(['stream','stream_import'].includes(j.kind)){await record(c,j,'stream_delivery_minutes',(p.providerDuration||0)/60,'estimated_full_export_attempt');await c.db.run('UPDATE jobs SET export_attempts=export_attempts+1 WHERE id=?',[j.id]);}
   phase='container_dispatch';await dispatchContainer(c,j,stub,input);await saveState(c,j,'container_running');return;
  }
  phase='container_status';const res=await stub.fetch('http://container/status');if(!res.ok)fail(502,'CONTAINER_STATUS_FAILED');const result=await res.json();await recordProgress(c,j,result.progress);if(result.diagnostics)await c.db.run('UPDATE jobs SET result_json=? WHERE id=?',[JSON.stringify({diagnostics:safeDiagnostics(result.diagnostics)}),j.id]);if(result.state==='running'||result.state==='starting'){await saveState(c,j,'container_running');return;}
  await recordContainer(c,j,result);if(result.state!=='done')fail(502,'PROCESSOR_FAILED',text(result.error||'Processor failed; see sanitized job log.','error',500));
  if(j.kind==='index'){await c.db.run("UPDATE videos SET index_status='processing' WHERE id=?",[v.id]);await saveState(c,j,'ai_index',null,{manifest:{...result.result,processorDiagnostics:safeDiagnostics(result.diagnostics)},index:0,visualPrompt:p.visualPrompt});return;}
  if(j.kind==='stream')await streamCleanup(c,j);
  await finish(c,j,'succeeded',{...result.result,processorDiagnostics:safeDiagnostics(result.diagnostics)});return;
 }
 if(j.kind==='semantic_search'){const matches=await semanticSearch(c,j.tenant_id,p,j);await finish(c,j,'succeeded',{items:matches});return;}
 if(j.kind==='ask'){await finish(c,j,'succeeded',await answerQuestion(c,j,v,p));return;}
 if(j.kind==='summarize'){const rows=await c.db.all('SELECT layer,start_seconds,text FROM artifacts WHERE video_id=? ORDER BY start_seconds LIMIT 200',[v.id]);if(!rows.length)fail(409,'INDEX_REQUIRED');const structured=renderSummary(await generateText(c,summaryPrompt(rows),j,undefined,summaryFormat()),rows);const summary=structured.summary;await checkJobAccess(c,j);await c.db.batch([...policyOps(c),['UPDATE videos SET summary=? WHERE id=?',[summary,v.id]]]);await finish(c,j,'succeeded',structured);return;}
 if(j.kind==='embed_artifacts'){const rows=await c.db.all('SELECT * FROM artifacts WHERE video_id=? AND vector_id IS NULL LIMIT 8',[v.id]);if(!c.env.VECTORS)fail(503,'VECTORIZE_NOT_ENABLED');if(!rows.length){await finish(c,j,'succeeded',{embedded:true});return;}const values=await embed(c,rows.map(r=>r.text),j);await c.env.VECTORS.upsert(rows.map((r,i)=>({id:r.id,namespace:j.tenant_id,values:values[i],metadata:{videoId:v.id,layer:r.layer}})));await record(c,j,'vector_query_dimensions',rows.length*384,'measured_dimensions');await c.db.batch(rows.map(r=>['UPDATE artifacts SET vector_id=id WHERE id=?',[r.id]]));await saveState(c,j,'embedding');return;}
 if(['generate_image','generate_speech'].includes(j.kind)){await finish(c,j,'succeeded',await generateAsset(c,j,v,p));return;}
 fail(400,'UNSUPPORTED_JOB');
 }catch(e){
  // Never blindly repeat a paid AI/provider call after an ambiguous transport failure.
  const code=e.code||'PROCESSING_ERROR';if(!e.code&&CONTAINER_KINDS.has(j.kind)){const prior=JSON.parse((await c.db.one('SELECT result_json FROM jobs WHERE id=?',[j.id]))?.result_json||'{}');await c.db.run('UPDATE jobs SET result_json=? WHERE id=?',[JSON.stringify({...prior,diagnostics:{...safeDiagnostics(prior.diagnostics),...startupDiagnostics(phase,e,code)}}),j.id]);}await event(c,j,'error',code==='PROCESSOR_FAILED'?`${code}: ${processorFailure(e.message)}`:code);if(c.env.MEDIA&&CONTAINER_KINDS.has(j.kind)){try{const stub=c.env.MEDIA.get(c.env.MEDIA.idFromName(j.id));await stub.fetch('http://container/cancel',{method:'POST'});}catch{}}
  try{const retained=await c.db.one('SELECT result_json FROM jobs WHERE id=?',[j.id]);const diagnostics=safeDiagnostics(JSON.parse(retained?.result_json||'{}').diagnostics);await finish(c,j,'failed',diagnostics?{diagnostics}:{},code);}catch(cleanup){await c.db.run("UPDATE jobs SET state='cleanup_required',last_error=?,next_run_at=?,lease_until=0,updated_at=? WHERE id=?",[code,now()+60000,now(),j.id]);await enqueue(c,j.id,60);}
 }
}
export async function recoverJobs(c){const jobs=await c.db.all('SELECT id FROM jobs WHERE finished_at IS NULL AND next_run_at<=? AND lease_until<? ORDER BY next_run_at LIMIT 100',[now(),now()]);for(const j of jobs)await enqueue(c,j.id);return jobs.length;}
