import {publicLineage} from './access/lineage.js';
import {moveGuard} from './access/moves.js';
import {agentOnly,videoAccess,videoFilter,accessMode,folderAccess,checkRevision,revisionOps,policyOps,humanOnly,permission} from './access/policy.js';
import {approvalOps} from './approvals/service.js';
import {claimOps} from './runs/claims.js';
import {tenantAuth,authenticate,roles} from './auth.js';
import {fail,uid,now,text,id,email,integer,choice,tagsInput,origins} from './util.js';
export async function tenantList(c){const a=await authenticate(c);if(a.type==='key')return c.db.all(agentOnly(c)?'SELECT id,name,slug,status FROM tenants WHERE id=?':'SELECT * FROM tenants WHERE id=?',[a.tenantId]);if(a.super)return c.db.all('SELECT * FROM tenants ORDER BY name');return c.db.all('SELECT t.*,m.role FROM tenants t JOIN members m ON m.tenant_id=t.id WHERE m.email=? ORDER BY t.name',[a.email]);}
export async function members(c,tid,b){await tenantAuth(c,tid,'videos:write','admin');if(c.actor.type==='key')fail(403,'SESSION_REQUIRED');if(!b)return c.db.all('SELECT email,role,created_at FROM members WHERE tenant_id=? ORDER BY email',[tid]);const addr=email(b.email),role=choice(b.role,Object.keys(roles),'role');
 if(role==='owner'&&!c.actor.super&&c.actor.role!=='owner')fail(403,'OWNER_REQUIRED');
 // Only the owner can demote another owner. Preserve the last owner atomically.
 const existing=await c.db.one('SELECT role FROM members WHERE tenant_id=? AND email=?',[tid,addr]);
 if(existing?.role==='owner'&&!c.actor.super&&c.actor.role!=='owner')fail(403,'OWNER_REQUIRED');
 if(existing?.role==='owner'&&role!=='owner'){const result=await c.db.run("UPDATE members SET role=? WHERE tenant_id=? AND email=? AND (SELECT COUNT(*) FROM members WHERE tenant_id=? AND role='owner')>1",[role,tid,addr,tid]);if(!result.meta.changes)fail(409,'LAST_OWNER');}
 else await c.db.run('INSERT INTO members(tenant_id,email,role,created_at) VALUES(?,?,?,?) ON CONFLICT(tenant_id,email) DO UPDATE SET role=excluded.role',[tid,addr,role,now()]);
 await c.db.audit(tid,c.actor.email,'member.upsert',addr,{role});return {ok:true};}
export async function removeMember(c,tid,address){await tenantAuth(c,tid,'videos:write','owner');if(c.actor.type==='key')fail(403,'SESSION_REQUIRED');const addr=email(address);const r=await c.db.run("DELETE FROM members WHERE tenant_id=? AND email=? AND (role!='owner' OR (SELECT COUNT(*) FROM members WHERE tenant_id=? AND role='owner')>1)",[tid,addr,tid]);if(!r.meta.changes)fail(409,'NOT_FOUND_OR_LAST_OWNER');await c.db.run('UPDATE sessions SET revoked_at=? WHERE email=?',[now(),addr]);await c.db.audit(tid,c.actor.email,'member.remove',addr);return {ok:true};}
export async function requireVideo(c,vid,scope='videos:read',minimum='viewer'){
 id(vid);const actor=await authenticate(c);
 if(actor.type==='key'){await tenantAuth(c,actor.tenantId,scope,minimum);permission(c,accessMode(scope));}
 const v=await c.db.one(`SELECT * FROM videos WHERE id=? AND status!='deleted' ${actor.type==='key'?'AND tenant_id=?':''}`,[vid,...(actor.type==='key'?[actor.tenantId]:[])]);
 if(!v)fail(404,'VIDEO_NOT_FOUND');await tenantAuth(c,v.tenant_id,scope,minimum);await videoAccess(c,v,accessMode(scope));return v;
}
export function publicVideo(v){const {upload_id,upload_key,...rest}=v;return {...rest,tags:JSON.parse(v.tags_json),allowedOrigins:JSON.parse(v.allowed_origins_json)};}
export async function listVideos(c,tid,q={}){await tenantAuth(c,tid);const filter=videoFilter(c);const where=['v.tenant_id=?',"v.status!='deleted'",filter.sql],args=[tid,...filter.args];if(q.folder!==undefined&&q.folder!=='all'){if(q.folder==='root')where.push('v.folder_id IS NULL');else{where.push('v.folder_id=?');args.push(id(q.folder));}}if(q.tag){where.push('EXISTS(SELECT 1 FROM video_tags vt JOIN tags t ON t.id=vt.tag_id WHERE vt.video_id=v.id AND t.tenant_id=? AND t.name=?)');args.push(tid,String(q.tag).toLowerCase());}
 if(q.q){where.push("(v.title LIKE ? ESCAPE '\\' OR v.description LIKE ? ESCAPE '\\')");const p='%'+String(q.q).slice(0,200).replace(/[\\%_]/g,'\\$&')+'%';args.push(p,p);}if(q.status){where.push('v.status=?');args.push(choice(q.status,['ready','processing','uploading','failed','deleting'],'status'));}
 const limit=integer(Number(q.limit||40),'limit',1,100),offset=integer(Number(q.offset||0),'offset',0,100000);const rows=await c.db.all(`SELECT v.*,(SELECT COALESCE(SUM(o.size),0) FROM objects o WHERE o.video_id=v.id AND o.status='ready') AS stored_bytes FROM videos v WHERE ${where.join(' AND ')} ORDER BY v.created_at DESC,v.id DESC LIMIT ? OFFSET ?`,[...args,limit+1,offset]);return {items:rows.slice(0,limit).map(publicVideo),nextOffset:rows.length>limit?offset+limit:null};}
export async function getVideo(c,vid){const v=await requireVideo(c,vid);return {...publicVideo(v),objects:await c.db.all("SELECT path,size,role,content_type,status FROM objects WHERE video_id=? AND status!='deleted' ORDER BY path",[vid])};}
export async function verifyFolder(c,tid,fid){if(fid!==null&&fid!==undefined&&!await c.db.one('SELECT id FROM folders WHERE id=? AND tenant_id=?',[id(fid),tid]))fail(400,'FOLDER_NOT_IN_TENANT');return fid??null;}
export function tagStatements(vid,tid,names){const statements=[['DELETE FROM video_tags WHERE video_id=?',[vid]]];for(const name of names){const tagId=uid('tag_');statements.push(['INSERT INTO tags(id,tenant_id,name) VALUES(?,?,?) ON CONFLICT(tenant_id,name) DO NOTHING',[tagId,tid,name]],['INSERT INTO video_tags(video_id,tag_id) SELECT ?,id FROM tags WHERE tenant_id=? AND name=?',[vid,tid,name]]);}statements.push(['UPDATE videos SET tags_json=?,updated_at=? WHERE id=? AND tenant_id=?',[JSON.stringify(names),now(),vid,tid]]);return statements;}
export async function applyTags(c,vid,tid,names){await c.db.batch(tagStatements(vid,tid,names));}
export async function updateVideo(c,vid,b){const v=await requireVideo(c,vid,'videos:write','editor');if(['deleting','deleted'].includes(v.status))fail(409,'VIDEO_DELETING');const folder=Object.hasOwn(b,'folderId')?await verifyFolder(c,v.tenant_id,b.folderId):v.folder_id;
 await checkRevision(c,v,b.expectedRevision);if(await c.db.one('SELECT id FROM jobs WHERE video_id=? AND finished_at IS NULL',[vid]))fail(409,'VIDEO_HAS_ACTIVE_JOB');if(folder!==v.folder_id&&agentOnly(c))fail(403,'ADMIN_MOVE_REVIEW_REQUIRED');
 const visibility=choice(b.visibility??v.visibility,['private','public','unlisted'],'visibility'),allowed=Object.hasOwn(b,'allowedOrigins')?origins(b.allowedOrigins):JSON.parse(v.allowed_origins_json);
 if(visibility!=='private')await publicLineage(c,{...v,visibility,allowed_origins_json:JSON.stringify(allowed)});const version=visibility!==v.visibility||JSON.stringify(allowed)!==v.allowed_origins_json?1:0;
 if(Object.hasOwn(b,'downloadsEnabled')&&typeof b.downloadsEnabled!=='boolean')fail(400,'INVALID_DOWNLOAD_POLICY');
 const sensitive=['visibility','allowedOrigins','downloadsEnabled','watermarkText','maxSessions'].some(k=>Object.hasOwn(b,k));const ops=[...(folder!==v.folder_id?await moveGuard(c,v.tenant_id,'video',vid,folder,b.moveReviewHash):[]),...policyOps(c),...revisionOps(c,'videos',v,b.expectedRevision),...claimOps(c,vid,b),...(sensitive?await approvalOps(c,v,'publish',b):[])];
 ops.push(['UPDATE videos SET title=?,description=?,folder_id=?,visibility=?,allowed_origins_json=?,watermark_text=?,max_sessions=?,downloads_enabled=?,token_version=token_version+?,revision=revision+1,updated_at=? WHERE id=? AND tenant_id=?',[
 text(b.title??v.title,'title',180),text(b.description??v.description,'description',4000,0),folder,visibility,JSON.stringify(allowed),text(b.watermarkText??v.watermark_text,'watermarkText',100,0),integer(b.maxSessions??v.max_sessions,'maxSessions',1,20),b.downloadsEnabled===undefined?v.downloads_enabled:b.downloadsEnabled?1:0,version,now(),vid,v.tenant_id]]);if(Object.hasOwn(b,'tags'))ops.push(...tagStatements(vid,v.tenant_id,tagsInput(b.tags)));await c.db.batch(ops);
 await c.db.audit(v.tenant_id,c.actor.email,'video.update',vid,{fields:Object.keys(b)});return getVideo(c,vid);}
export async function bulkVideos(c,tid,b){await tenantAuth(c,tid,'videos:write','editor');if(!Array.isArray(b.ids)||b.ids.length<1||b.ids.length>50)fail(400,'INVALID_BULK');const out=[];for(const vid of [...new Set(b.ids)]){const v=await requireVideo(c,vid,'videos:write','editor');if(v.tenant_id!==tid)fail(403,'TENANT_MISMATCH');out.push(v);}const patch={};if(agentOnly(c))fail(400,'USE_VERSIONED_SINGLE_EDITS');if(Object.hasOwn(b,'folderId'))patch.folderId=await verifyFolder(c,tid,b.folderId);for(const v of out){if(b.addTags)patch.tags=[...new Set([...JSON.parse(v.tags_json),...tagsInput(b.addTags)])];await updateVideo(c,v.id,patch);}return {updated:out.map(v=>v.id)};}
export async function folderList(c,tid){await tenantAuth(c,tid);if(agentOnly(c)&&!c.actor.permissions.some(p=>['read','write'].includes(p)))return [];const af=videoFilter(c);return c.db.all(`SELECT f.*,(SELECT COUNT(DISTINCT g.agent_id)>1 FROM agent_grants g WHERE g.resource_type='folder' AND g.resource_id=f.id) shared_agents,(SELECT COUNT(*) FROM videos v WHERE v.folder_id=f.id AND v.status!='deleted' AND ${af.sql}) video_count FROM folders f WHERE tenant_id=? ${agentOnly(c)?'AND EXISTS(SELECT 1 FROM agent_folder_access a WHERE a.folder_id=f.id AND a.agent_id=?)':''} ORDER BY name`,[...af.args,tid,...(agentOnly(c)?[c.actor.agentId]:[])]);}
export {folderWrite,folderDelete} from './access/folders.js';
export async function tagList(c,tid){await tenantAuth(c,tid);const af=videoFilter(c);return c.db.all(`SELECT t.*,COUNT(v.id) video_count FROM tags t LEFT JOIN video_tags vt ON vt.tag_id=t.id LEFT JOIN videos v ON v.id=vt.video_id AND v.status!='deleted' AND ${af.sql} WHERE t.tenant_id=? GROUP BY t.id ${agentOnly(c)?'HAVING COUNT(v.id)>0':''} ORDER BY t.name`,[...af.args,tid]);}
export async function tagWrite(c,tid,b,tagId){await tenantAuth(c,tid,'tags:write','editor');if(agentOnly(c))fail(403,'HUMAN_ADMIN_REQUIRED');const name=tagsInput([b.name])[0];if(tagId){const t=await c.db.one('SELECT * FROM tags WHERE id=? AND tenant_id=?',[tagId,tid]);if(!t)fail(404,'TAG_NOT_FOUND');await c.db.run('UPDATE tags SET name=? WHERE id=? AND tenant_id=?',[name,tagId,tid]);const videos=await c.db.all('SELECT v.id FROM videos v JOIN video_tags vt ON vt.video_id=v.id WHERE vt.tag_id=? AND v.tenant_id=?',[tagId,tid]);for(const v of videos){const names=(await c.db.all('SELECT t.name FROM tags t JOIN video_tags vt ON vt.tag_id=t.id WHERE vt.video_id=? ORDER BY t.name',[v.id])).map(t=>t.name);await c.db.run('UPDATE videos SET tags_json=? WHERE id=?',[JSON.stringify(names),v.id]);}}else{tagId=uid('tag_');await c.db.run('INSERT INTO tags(id,tenant_id,name) VALUES(?,?,?)',[tagId,tid,name]);}await c.db.audit(tid,c.actor.email,'tag.save',tagId,{name});return {id:tagId,name};}
export async function tagDelete(c,tid,tagId){await tenantAuth(c,tid,'tags:write','editor');if(agentOnly(c))fail(403,'HUMAN_ADMIN_REQUIRED');const tag=await c.db.one('SELECT * FROM tags WHERE id=? AND tenant_id=?',[tagId,tid]);if(!tag)fail(404,'TAG_NOT_FOUND');const vs=await c.db.all('SELECT v.* FROM videos v JOIN video_tags vt ON vt.video_id=v.id WHERE vt.tag_id=? AND v.tenant_id=?',[tagId,tid]);for(const v of vs)await applyTags(c,v.id,tid,JSON.parse(v.tags_json).filter(n=>n!==tag.name));await c.db.run('DELETE FROM tags WHERE id=? AND tenant_id=?',[tagId,tid]);return {ok:true};}
