import {lineage,publicLineage,approvalLineage} from './access/lineage.js';
import {bindKey,videoFilter,videoAccess,permission,policyOps} from './access/policy.js';
import {approvalOps} from './approvals/service.js';
import {tenantAuth,isSuper} from './auth.js';
import {signToken,verifyToken} from './crypto.js';
import {requireVideo} from './library.js';
import {getObject,rewriteHls} from './storage.js';
import {fail,uid,now,hash,randomToken,text,integer,number,assetPath,parseRange} from './util.js';
function mediaUrl(c,v,path,token){return `${c.env.APP_ORIGIN}/media/${v.id}/${path}?token=${encodeURIComponent(token)}`;}
async function tokenFor(c,v,sid){return signToken({scope:'playback',sid,vid:v.id,tid:v.tenant_id,pv:v.token_version},c.env.SIGNING_SECRET,Math.min(1800,Number(c.env.PLAYBACK_TTL_SECONDS||900)));}
function originAllowed(c,v){const configured=JSON.parse(v.allowed_origins_json);const origin=c.req.headers.get('origin');if(origin&&origin!==c.env.APP_ORIGIN&&configured.length&&!configured.includes(origin))fail(403,'PLAYBACK_ORIGIN_REJECTED');return origin;}
export async function startPlayback(c,b){if(c.req.headers.has('authorization'))await requireVideo(c,b.videoId,'playback:create','viewer');const vid=text(b.videoId,'videoId',80);const v=await c.db.one("SELECT * FROM videos WHERE id=? AND status IN ('ready','processing')",[vid]);if(!v)fail(404,'VIDEO_NOT_READY');const tenant=await c.db.one('SELECT * FROM tenants WHERE id=? AND status=?',[v.tenant_id,'active']);if(!tenant)fail(404,'VIDEO_UNAVAILABLE');c.meter.tenantId=v.tenant_id;c.meter.videoId=vid;originAllowed(c,v);
 let identity='';let shareId=null,issuerSession=null,issuerKey=null;
 if(b.shareToken){const share=await c.db.one('SELECT id,inputs_json,video_revision FROM share_links WHERE token_hash=? AND video_id=? AND revoked_at IS NULL AND expires_at>?',[await hash(text(b.shareToken,'shareToken',100)),vid,now()]);if(!share)fail(401,'SHARE_LINK_EXPIRED');if(share.video_revision!==v.revision)fail(401,'SHARE_VERSION_CHANGED');await approvalLineage(c,vid,JSON.parse(share.inputs_json));shareId=share.id;identity=`share:${share.id}:${c.req.headers.get('CF-Connecting-IP')||'local'}`;}
 else if(v.visibility==='private'||c.req.headers.has('authorization')){await tenantAuth(c,v.tenant_id,'playback:create','viewer');await videoAccess(c,v);identity=c.actor.type==='key'?`key-viewer:${text(b.viewerId??c.actor.email,'viewerId',160)}`:c.actor.email;issuerSession=c.actor.sessionId||null;issuerKey=c.actor.type==='key'?c.actor.email.slice(4):null;}
 else {await publicLineage(c,v);identity=`public:${c.req.headers.get('CF-Connecting-IP')||'local'}:${(c.req.headers.get('user-agent')||'').slice(0,200)}`;}
 const viewerHash=await hash(`${c.env.SIGNING_SECRET}:${v.tenant_id}:${identity}`),sid=uid('ps_'),ts=now(),expires=ts+8*3600000;
 const device=/mobile|android|iphone/i.test(c.req.headers.get('user-agent')||'')?'mobile':'desktop',country=c.req.cf?.country||'XX';
 const recent=await c.db.one('SELECT COUNT(*) n FROM play_sessions WHERE video_id=? AND viewer_hash=? AND created_at>?',[vid,viewerHash,ts-60000]);if(recent.n>=20)fail(429,'PLAYBACK_RATE_LIMIT');
 const r=await c.db.run(`INSERT INTO play_sessions(id,tenant_id,video_id,viewer_hash,issuer_session_id,issuer_key_id,country,device,created_at,expires_at,last_server_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM play_sessions WHERE video_id=? AND viewer_hash=? AND revoked_at IS NULL AND expires_at>? AND last_server_at>?)<?`,[sid,v.tenant_id,vid,viewerHash,issuerSession,issuerKey,country,device,ts,expires,ts,vid,viewerHash,ts,ts-90000,v.max_sessions]);if(!r.meta.changes)fail(429,'CONCURRENT_PLAYBACK_LIMIT','Close another active playback session.');
 // Link-bound sessions must be revoked when their originating link is revoked.
 if(shareId)await c.db.run('UPDATE play_sessions SET share_id=? WHERE id=?',[shareId,sid]);
 const token=await tokenFor(c,v,sid);return playbackResponse(c,v,sid,token,expires,viewerHash);
}
async function playbackResponse(c,v,sid,token,expires,viewerHash){const tracks=await c.db.all("SELECT id,language,label,is_default,path FROM media_tracks WHERE video_id=? AND kind='captions' AND status='active'",[v.id]);return {captionTracks:tracks.map(t=>({...t,url:mediaUrl(c,v,t.path,token)})),preview:v.preview_path?mediaUrl(c,v,v.preview_path,token):null,sprite:v.sprite_path?mediaUrl(c,v,v.sprite_path,token):null,spriteLayout:JSON.parse(v.preview_meta_json||'null'),sessionId:sid,videoId:v.id,title:v.title,kind:v.kind,encrypted:!!v.encrypted,token,expiresAt:expires,renewAfterSeconds:Math.floor(Number(c.env.PLAYBACK_TTL_SECONDS||900)*.6),url:mediaUrl(c,v,v.primary_path,token),poster:v.thumbnail_path?mediaUrl(c,v,v.thumbnail_path,token):null,captions:v.caption_path?mediaUrl(c,v,v.caption_path,token):null,watermark:v.watermark_text||`${v.visibility==='private'?'Private • ':''}${viewerHash.slice(0,8)}`,durationSeconds:v.duration_seconds,protection:'access-control and optional AES-128 HLS; NOT DRM'};}
export async function validatePlayback(c,token){const p=await verifyToken(token,c.env.SIGNING_SECRET,'playback');const s=await c.db.one(`SELECT p.*,v.title,v.kind,v.status video_status,v.token_version,v.primary_path,v.source_path,v.thumbnail_path,v.caption_path,v.preview_path,v.sprite_path,v.preview_meta_json,v.allowed_origins_json,v.watermark_text,v.duration_seconds,v.encrypted,v.visibility,v.revision video_revision,t.status tenant_status,sl.revoked_at share_revoked,sl.expires_at share_expires,sl.inputs_json share_inputs,sl.video_revision share_revision,iss.email issuer_email,iss.revoked_at issuer_session_revoked,iss.expires_at issuer_session_expires,ik.id valid_issuer_key,ik.revoked_at issuer_key_revoked,ik.expires_at issuer_key_expires,EXISTS(SELECT 1 FROM members m WHERE m.email=iss.email AND m.tenant_id=p.tenant_id) issuer_member FROM play_sessions p JOIN videos v ON v.id=p.video_id JOIN tenants t ON t.id=p.tenant_id LEFT JOIN share_links sl ON sl.id=p.share_id LEFT JOIN sessions iss ON iss.id=p.issuer_session_id LEFT JOIN api_keys ik ON ik.id=p.issuer_key_id AND ik.tenant_id=p.tenant_id WHERE p.id=?`,[p.sid]);
 if(!s||s.video_id!==p.vid||s.tenant_id!==p.tid||s.revoked_at||s.expires_at<=now()||s.token_version!==p.pv||s.tenant_status!=='active'||!['ready','processing'].includes(s.video_status)||(s.share_id&&(s.share_revoked||s.share_expires<=now())))fail(401,'PLAYBACK_REVOKED');if(s.issuer_session_id&&(!s.issuer_email||s.issuer_session_revoked||s.issuer_session_expires<=now()||(!s.issuer_member&&!isSuper(c.env,s.issuer_email))))fail(401,'PLAYBACK_ISSUER_REVOKED');if(s.issuer_key_id&&(!s.valid_issuer_key||s.issuer_key_revoked||s.issuer_key_expires<=now()))fail(401,'PLAYBACK_ISSUER_REVOKED');if(s.share_id){if(s.share_revision!==s.video_revision)fail(401,'SHARE_VERSION_CHANGED');await approvalLineage(c,s.video_id,JSON.parse(s.share_inputs));}else if(!s.issuer_key_id&&!s.issuer_session_id)await publicLineage(c,{...s,id:s.video_id});if(s.issuer_key_id){await bindKey(c,s.issuer_key_id);await videoAccess(c,{id:s.video_id});}c.meter.tenantId=s.tenant_id;c.meter.videoId=s.video_id;originAllowed(c,s);return {p,s};}
export async function renewPlayback(c,b){const {s}=await validatePlayback(c,text(b.token,'token',8192));const v={...s,id:s.video_id,token_version:s.token_version};return playbackResponse(c,v,s.id,await tokenFor(c,v,s.id),s.expires_at,s.viewer_hash);}
export async function stopPlayback(c,b){const {s}=await validatePlayback(c,b.token);await c.db.run('UPDATE play_sessions SET revoked_at=? WHERE id=?',[now(),s.id]);return {ok:true};}
export async function media(c,vid,path){c.meter.category='media';const token=new URL(c.req.url).searchParams.get('token'),{s}=await validatePlayback(c,token);if(s.video_id!==vid)fail(403,'TOKEN_RESOURCE_MISMATCH');path=assetPath(path);let object=await c.db.one("SELECT * FROM objects WHERE video_id=? AND tenant_id=? AND path=? AND status='ready'",[vid,s.tenant_id,path]);let alias=false;
 if(!object){object=await c.db.one("SELECT o.* FROM media_aliases a JOIN objects o ON o.id=a.source_object_id JOIN videos v ON v.id=o.video_id WHERE a.video_id=? AND a.tenant_id=? AND a.path=? AND o.status='ready' AND v.status IN ('ready','processing')",[vid,s.tenant_id,path]);alias=!!object;}
 if(!object)fail(404,'MEDIA_NOT_FOUND');
 const primaryFolder=s.primary_path.includes('/')?s.primary_path.slice(0,s.primary_path.lastIndexOf('/')+1):'';
 const caption=object.role==='caption'&&await c.db.one("SELECT id FROM media_tracks WHERE video_id=? AND path=? AND status='active'",[vid,path]);
 const permitted=alias||!!caption||path===s.preview_path||path===s.sprite_path||path===s.primary_path||path===s.caption_path||path===s.thumbnail_path||(s.kind==='hls'&&object.role==='playback'&&path.startsWith(primaryFolder));if(!permitted)fail(403,'ASSET_NOT_PLAYABLE');
 const origin=c.req.headers.get('origin'),headers=new Headers({'Content-Type':object.content_type,'Accept-Ranges':'bytes','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cache-Control':'private, no-store','Vary':'Origin'});if(origin)headers.set('Access-Control-Allow-Origin',origin);headers.set('Access-Control-Expose-Headers','Content-Range,Content-Length,Accept-Ranges');
 if(path.endsWith('.m3u8')){const file=await getObject(c,object.object_key);if(!file)fail(404,'MEDIA_NOT_FOUND');const manifest=rewriteHls(await file.text(),path,p=>mediaUrl(c,{id:vid},p,token));return new Response(c.req.method==='HEAD'?null:manifest,{headers});}
 const range=parseRange(c.req.headers.get('range'),object.size);headers.set('Content-Length',String(range?.length??object.size));headers.set('ETag',`"${object.etag}"`);if(range)headers.set('Content-Range',`bytes ${range.offset}-${range.end}/${object.size}`);
 if(c.req.method==='HEAD')return new Response(null,{status:range?206:200,headers});c.meter.add('bytes_offered',range?.length??object.size);
 // Authorization above runs on EVERY request, including cache hits. Never cache tokens or encryption keys.
 const cacheable=!range&&!path.endsWith('.key')&&object.size<=32*1024*1024&&typeof caches!=='undefined';const key=new Request(`${c.env.APP_ORIGIN}/__internal_cache/${object.id}/${object.etag}`);
 if(cacheable){const hit=await caches.default.match(key);if(hit){c.meter.add('cache_hit');return new Response(hit.body,{headers});}}
 const file=await getObject(c,object.object_key,range?{range:{offset:range.offset,length:range.length}}:undefined);if(!file)fail(404,'MEDIA_NOT_FOUND');
 let result=new Response(file.body,{status:range?206:200,headers});if(cacheable){const cached=new Response(result.clone().body,{headers:{'Content-Type':object.content_type,'Content-Length':String(object.size),'Cache-Control':'public,max-age=31536000'}});c.ctx.waitUntil(caches.default.put(key,cached).catch(()=>{}));}return result;
}
export async function heartbeat(c,b){const {s}=await validatePlayback(c,b.token),seq=integer(b.seq,'seq',1,1e9);if(seq<=s.seq)return {accepted:false};const ts=now(),elapsed=Math.max(0,Math.min(60,(ts-s.last_server_at)/1000));const watch=Math.min(number(b.watchSeconds??0,'watchSeconds',0,120),elapsed*2+1),buffer=Math.min(number(b.bufferSeconds??0,'bufferSeconds',0,120),elapsed+1),position=Math.min(number(b.position??0,'position',0,86400),s.duration_seconds||86400);
 const r=await c.db.run('UPDATE play_sessions SET seq=?,started_at=COALESCE(started_at,?),last_server_at=?,watch_seconds=watch_seconds+?,buffer_seconds=buffer_seconds+?,max_position=MAX(max_position,?),startup_ms=CASE WHEN startup_ms=0 THEN ? ELSE startup_ms END,completed=MAX(completed,?),errors=errors+? WHERE id=? AND seq<?',[seq,ts,ts,watch,buffer,position,number(b.startupMs??0,'startupMs',0,120000),b.completed?1:0,b.error?1:0,s.id,seq]);return {accepted:!!r.meta.changes};}
export async function revokePlayback(c,vid){const v=await requireVideo(c,vid,'videos:write','editor');permission(c,'publish');await c.db.batch([['UPDATE videos SET token_version=token_version+1 WHERE id=?',[vid]],['UPDATE play_sessions SET revoked_at=? WHERE video_id=? AND revoked_at IS NULL',[now(),vid]]]);await c.db.audit(v.tenant_id,c.actor.email,'video.revoke_playback',vid);return {ok:true};}
export async function createShare(c,vid,b){const v=await requireVideo(c,vid,'videos:write','editor'),days=integer(b.days??7,'days',1,90),token=randomToken(),sid=uid('share_');await c.db.batch([...policyOps(c),...await approvalOps(c,v,'share',b),['INSERT INTO share_links(id,tenant_id,video_id,token_hash,expires_at,created_at,inputs_json,video_revision) VALUES(?,?,?,?,?,?,?,?)',[sid,v.tenant_id,vid,await hash(token),now()+days*86400000,now(),JSON.stringify(await lineage(c,vid)),v.revision]]]);await c.db.audit(v.tenant_id,c.actor.email,'video.share.create',sid);return {id:sid,url:`${c.env.APP_ORIGIN}/watch/${vid}#share=${token}`,expiresAt:now()+days*86400000};}
export async function revokeShare(c,vid,sid){await requireVideo(c,vid,'videos:write','editor');permission(c,'share');await c.db.run('UPDATE share_links SET revoked_at=? WHERE id=? AND video_id=?',[now(),sid,vid]);return {ok:true};}
export async function analytics(c,tid,q={}){await tenantAuth(c,tid,'analytics:read','admin');const days=integer(Number(q.days||30),'days',1,365),start=now()-days*86400000,args=[tid,start];const af=videoFilter(c);let extra=` AND video_id IN (SELECT v.id FROM videos v WHERE ${af.sql})`;args.push(...af.args);if(q.videoId){extra+=' AND video_id=?';args.push(text(q.videoId,'videoId',80));}
 const totals=await c.db.one(`SELECT COUNT(*) sessions,COUNT(DISTINCT viewer_hash) unique_viewers,COALESCE(SUM(watch_seconds),0)/3600 watch_hours,COALESCE(SUM(buffer_seconds),0) buffer_seconds,COALESCE(AVG(NULLIF(startup_ms,0)),0) average_startup_ms,COALESCE(SUM(completed),0) completions,COALESCE(SUM(errors),0) errors FROM play_sessions WHERE tenant_id=? AND created_at>?${extra}`,args);
 const daily=await c.db.all(`SELECT strftime('%Y-%m-%d',created_at/1000,'unixepoch') day,COUNT(*) sessions,SUM(watch_seconds)/3600 watch_hours,SUM(completed) completions FROM play_sessions WHERE tenant_id=? AND created_at>?${extra} GROUP BY day ORDER BY day`,args);
 const geography=await c.db.all(`SELECT country,COUNT(*) sessions,SUM(watch_seconds)/3600 watch_hours FROM play_sessions WHERE tenant_id=? AND created_at>?${extra} GROUP BY country ORDER BY sessions DESC LIMIT 20`,args);
 const videos=await c.db.all(`SELECT v.id,v.title,COUNT(p.id) sessions,COALESCE(SUM(p.watch_seconds),0)/3600 watch_hours,COALESCE(SUM(p.completed),0) completions FROM videos v LEFT JOIN play_sessions p ON p.video_id=v.id AND p.created_at>? WHERE v.tenant_id=? AND v.status!='deleted' AND ${af.sql} GROUP BY v.id ORDER BY watch_hours DESC LIMIT 30`,[start,tid,...af.args]);
 const delivery=await c.db.one(`SELECT COALESCE(SUM(requests),0) requests,COALESCE(SUM(bytes_offered),0) bytes_offered,COALESCE(SUM(cache_hits),0) cache_hits FROM video_usage_daily WHERE tenant_id=? AND day>=? AND video_id IN (SELECT v.id FROM videos v WHERE ${af.sql})${q.videoId?' AND video_id=?':''}`,[tid,new Date(start).toISOString().slice(0,10),...af.args,...(q.videoId?[q.videoId]:[])]);
 return {days,totals,daily,geography,videos,delivery,note:'Watch telemetry is client-reported and capped by server elapsed time; it is not used for supplier billing. Bytes offered are not proof of bytes consumed.'};}
