import {bytesHash,partFingerprint} from './artifacts/fingerprint.js';
import {agentOnly,folderAccess,policyOps} from './access/policy.js';
import {tenantAuth} from './auth.js';
import {requireVideo,verifyFolder,applyTags,publicVideo} from './library.js';
import {fail,uid,now,text,id,integer,number,choice,bodyBytes,assetPath,objectKey,contentType,tagsInput} from './util.js';
export const PART_SIZE=8*1024*1024;
export async function reserveObject(c,v,path,size,role='source'){
 path=assetPath(path);size=integer(size,'size',0,Number(c.env.MAX_VIDEO_BYTES||4294967296));const key=objectKey(v.tenant_id,v.id,path),existing=await c.db.one('SELECT * FROM objects WHERE video_id=? AND path=?',[v.id,path]);
 if(existing){if(existing.status==='deleted')fail(409,'PATH_TOMBSTONED','Use a new versioned object path.');if(existing.size!==size)fail(409,'SIZE_MISMATCH');return existing;}
 const oid=uid('o_');await c.db.batch([...policyOps(c),['INSERT INTO objects(id,tenant_id,video_id,path,object_key,size,content_type,role,created_at,agent_id) VALUES(?,?,?,?,?,?,?,?,?,?)',[oid,v.tenant_id,v.id,path,key,size,contentType(path),role,now(),agentOnly(c)?c.actor.agentId:v.agent_id??null]]]);return {id:oid,object_key:key,size,path,role,content_type:contentType(path),status:'reserved'};
}
export async function putObject(c,v,path,data,role='playback'){
 const size=data.byteLength??data.length;if(!Number.isSafeInteger(size))throw new Error('putObject requires bounded bytes');const o=await reserveObject(c,v,path,size,role);if(o.status==='ready')return o;
 c.meter.add('r2_a');const result=await c.env.VIDEOS.put(o.object_key,data,{httpMetadata:{contentType:contentType(path)}});
 await c.db.batch([...policyOps(c),["UPDATE objects SET etag=?,content_hash=?,status='ready',stored_at=COALESCE(stored_at,?) WHERE id=?",[result.etag,await bytesHash(data),now(),o.id]]]);return {...o,status:'ready',etag:result.etag};
}
export async function getObject(c,key,options){c.meter.add('r2_b');return c.env.VIDEOS.get(key,options);}
export async function createVideo(c,tid,b){await tenantAuth(c,tid,'videos:write','editor');const kind=choice(b.kind??'mp4',['mp4','hls','webm','mov','audio','image'],'kind'),folder=await verifyFolder(c,tid,b.folderId??null),title=text(b.title,'title',180),vid=uid('v_');const size=integer(b.size??0,'size',0,Number(c.env.MAX_VIDEO_BYTES||4294967296));if(kind!=='hls'&&size===0)fail(400,'EMPTY_UPLOAD');
 await folderAccess(c,tid,folder,'write');
 const ext=kind==='audio'?choice(b.extension??'mp3',['mp3','m4a','wav'],'extension'):kind==='image'?choice(b.extension??'jpg',['jpg','png'],'extension'):kind;
 const primary=kind==='hls'?assetPath(b.primaryPath??'master.m3u8'):`source.${ext}`;if(kind==='hls'&&!primary.endsWith('.m3u8'))fail(400,'HLS_PLAYLIST_REQUIRED');
 await c.db.run('INSERT INTO videos(id,tenant_id,folder_id,title,kind,primary_path,source_path,expected_bytes,duration_seconds,width,height,created_at,updated_at,agent_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[vid,tid,folder,title,kind,primary,primary,size,number(b.durationSeconds??0,'durationSeconds',0,86400),integer(b.width??0,'width',0,16384),integer(b.height??0,'height',0,16384),now(),now(),agentOnly(c)?c.actor.agentId:null]);const v=await c.db.one('SELECT * FROM videos WHERE id=?',[vid]);
 if(b.tags)await applyTags(c,vid,tid,tagsInput(b.tags));
 if(kind!=='hls'){try{const o=await reserveObject(c,v,primary,size,'source');c.meter.add('r2_a');const m=await c.env.VIDEOS.createMultipartUpload(o.object_key,{httpMetadata:{contentType:contentType(primary)}});await c.db.run('UPDATE videos SET upload_id=?,upload_key=? WHERE id=?',[m.uploadId,m.key,vid]);}catch(e){await c.db.run("UPDATE videos SET status='failed',last_error='Upload initialization failed',updated_at=? WHERE id=?",[now(),vid]);await c.db.run("UPDATE objects SET status='deleted',deleted_at=? WHERE video_id=? AND status='reserved'",[now(),vid]);throw e;}}
 await c.db.audit(tid,c.actor.email,'video.create',vid,{title,kind,size});return {...publicVideo(v),partSize:PART_SIZE,parts:Math.ceil(size/PART_SIZE)};
}
export async function uploadPart(c,vid,n){const v=await requireVideo(c,vid,'videos:write','editor');if(v.status!=='uploading'||!v.upload_id)fail(409,'NOT_UPLOADING');n=integer(Number(n),'partNumber',1,Math.ceil(v.expected_bytes/PART_SIZE));const expected=Math.min(PART_SIZE,v.expected_bytes-(n-1)*PART_SIZE);const bytes=await bodyBytes(c.req,PART_SIZE);if(bytes.length!==expected)fail(400,'PART_SIZE_MISMATCH');
 if(n===1&&v.kind==='mp4'&&(bytes.length<12||new TextDecoder().decode(bytes.slice(4,8))!=='ftyp'))fail(400,'INVALID_MP4_HEADER','Upload an actual MP4, or choose the correct source format.');
 const upload=c.env.VIDEOS.resumeMultipartUpload(v.upload_key,v.upload_id);c.meter.add('r2_a');const part=await upload.uploadPart(n,bytes);const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
 await c.db.run('INSERT INTO upload_parts(video_id,part_number,etag,sha256,size,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(video_id,part_number) DO UPDATE SET etag=excluded.etag,sha256=excluded.sha256,size=excluded.size',[vid,n,part.etag,sha256,bytes.length,now()]);await c.db.run('UPDATE videos SET updated_at=? WHERE id=?',[now(),vid]);return {partNumber:n,etag:part.etag,sha256,size:bytes.length};}
export async function uploadStatus(c,vid){const v=await requireVideo(c,vid,'videos:write','editor');return {id:vid,status:v.status,expectedBytes:v.expected_bytes,partSize:PART_SIZE,parts:await c.db.all('SELECT part_number,etag,sha256,size FROM upload_parts WHERE video_id=? AND retired_at IS NULL ORDER BY part_number',[vid])};}
export async function completeUpload(c,vid){const v=await requireVideo(c,vid,'videos:write','editor');if(v.status==='ready')return publicVideo(v);if(v.kind==='hls')return finaliseHls(c,v);if(v.status!=='uploading'||!v.upload_id)fail(409,'NOT_UPLOADING');
 const parts=await c.db.all('SELECT * FROM upload_parts WHERE video_id=? AND retired_at IS NULL ORDER BY part_number',[vid]),count=Math.ceil(v.expected_bytes/PART_SIZE);if(parts.length!==count||parts.some((p,i)=>p.part_number!==i+1)||parts.reduce((a,p)=>a+p.size,0)!==v.expected_bytes)fail(409,'UPLOAD_INCOMPLETE');
 let object;try{c.meter.add('r2_a');object=await c.env.VIDEOS.resumeMultipartUpload(v.upload_key,v.upload_id).complete(parts.map(p=>({partNumber:p.part_number,etag:p.etag})));}catch(e){c.meter.add('r2_b');object=await c.env.VIDEOS.head(v.upload_key);if(!object||object.size!==v.expected_bytes)throw e;}
 const fingerprint=await partFingerprint(parts,object.size);await c.db.batch([...policyOps(c),["UPDATE objects SET status='ready',stored_at=COALESCE(stored_at,?),etag=?,content_hash=? WHERE video_id=? AND path=?",[now(),object.etag,fingerprint?'parts:'+fingerprint:null,vid,v.source_path]],["UPDATE videos SET status='ready',uploaded_at=?,updated_at=? WHERE id=? AND status='uploading'",[now(),now(),vid]],['UPDATE upload_parts SET retired_at=? WHERE video_id=? AND retired_at IS NULL',[now(),vid]]]);await c.db.audit(v.tenant_id,c.actor.email,'video.upload.complete',vid,{size:object.size});return publicVideo(await c.db.one('SELECT * FROM videos WHERE id=?',[vid]));}
export async function uploadHlsAsset(c,vid,path){const v=await requireVideo(c,vid,'videos:write','editor');if(v.kind!=='hls'||v.status!=='uploading')fail(409,'NOT_HLS_UPLOAD');path=assetPath(path);if(!['m3u8','ts','m4s','mp4','key','vtt','jpg','png'].includes(path.split('.').pop()))fail(400,'UNSUPPORTED_HLS_ASSET');const bytes=await bodyBytes(c.req,32*1024*1024);if(path.endsWith('.key')&&bytes.length!==16)fail(400,'AES_KEY_MUST_BE_16_BYTES');return putObject(c,v,path,bytes,path.endsWith('.vtt')?'caption':path.endsWith('.jpg')||path.endsWith('.png')?'thumbnail':'playback');}
export function resolveHlsUri(base,uri){if(!uri||uri.includes('?')||uri.includes('#')||uri.includes('%')||uri.includes('\\')||uri.startsWith('/')||uri.includes(':'))fail(400,'UNSAFE_HLS_URI');const baseUrl=new URL(base,'https://assets.invalid/');const url=new URL(uri,baseUrl);if(url.origin!==baseUrl.origin)fail(400,'UNSAFE_HLS_URI');return assetPath(url.pathname.slice(1));}
export function hlsReferences(manifest,base){if(!manifest.startsWith('#EXTM3U')||manifest.length>1024*1024)fail(400,'INVALID_HLS');const refs=[];for(const raw of manifest.split(/\r?\n/)){const line=raw.trim();if(!line)continue;if(line.startsWith('#')){for(const m of line.matchAll(/URI="([^"]+)"/g))refs.push(resolveHlsUri(base,m[1]));if(/#EXT-X-KEY:/.test(line)&&!/METHOD=(AES-128|NONE)(?:,|$)/.test(line))fail(400,'UNSUPPORTED_HLS_ENCRYPTION');}else refs.push(resolveHlsUri(base,line));}return refs;}
export function rewriteHls(manifest,base,makeUrl){hlsReferences(manifest,base);return manifest.split(/\r?\n/).map(raw=>{const line=raw.trim();if(!line)return raw;if(line.startsWith('#'))return raw.replace(/URI="([^"]+)"/g,(_,uri)=>`URI="${makeUrl(resolveHlsUri(base,uri))}"`);return makeUrl(resolveHlsUri(base,line));}).join('\n');}
async function finaliseHls(c,v){const objects=await c.db.all("SELECT * FROM objects WHERE video_id=? AND status='ready'",[v.id]),paths=new Set(objects.map(o=>o.path));if(!paths.has(v.primary_path))fail(400,'MASTER_PLAYLIST_MISSING');const manifests=objects.filter(o=>o.path.endsWith('.m3u8'));if(manifests.length>100)fail(400,'TOO_MANY_PLAYLISTS');let encrypted=false,duration=0;for(const m of manifests){const object=await getObject(c,m.object_key);if(!object)fail(409,'ASSET_MISSING');const value=await object.text();for(const ref of hlsReferences(value,m.path))if(!paths.has(ref))fail(400,'HLS_REFERENCE_MISSING',`Missing ${ref}`);encrypted||=value.includes('METHOD=AES-128');const sum=[...value.matchAll(/#EXTINF:([0-9.]+)/g)].reduce((a,x)=>a+Number(x[1]),0);duration=Math.max(duration,sum);}
 await c.db.run("UPDATE videos SET status='ready',encrypted=?,duration_seconds=?,uploaded_at=?,updated_at=? WHERE id=?",[encrypted?1:0,duration,now(),now(),v.id]);await c.db.audit(v.tenant_id,c.actor.email,'video.hls.finalise',v.id,{assets:objects.length,encrypted});return publicVideo(await c.db.one('SELECT * FROM videos WHERE id=?',[v.id]));}
export async function deleteObjects(c,v,limit=100){const objects=await c.db.all("SELECT * FROM objects WHERE video_id=? AND status!='deleted' LIMIT ?",[v.id,limit]);if(!objects.length)return true;await c.env.VIDEOS.delete(objects.map(o=>o.object_key));c.meter.add('r2_delete',objects.length);await c.db.batch(objects.map(o=>["UPDATE objects SET status='deleted',deleted_at=COALESCE(deleted_at,?) WHERE id=?",[now(),o.id]]));return objects.length<limit;}
