import {agentOnly,videoFilter,checkRevision,revisionOps,policyOps} from './access/policy.js';
import {tenantAuth} from './auth.js';
import {requireVideo,verifyFolder} from './library.js';
import {fail,uid,now,text,integer,number,allowedExternal,randomToken,enc} from './util.js';
import {seal,unseal} from './crypto.js';
export async function timelines(c,tid){await tenantAuth(c,tid,'videos:read','viewer');const af=videoFilter(c);return (await c.db.all(`SELECT t.* FROM timelines t WHERE tenant_id=? AND NOT EXISTS(SELECT 1 FROM json_each(json_extract(t.spec_json,'$.clips')) x WHERE NOT EXISTS(SELECT 1 FROM videos v WHERE v.id=json_extract(x.value,'$.videoId') AND ${af.sql})) ORDER BY updated_at DESC`,[tid,...af.args])).map(t=>({...t,spec:JSON.parse(t.spec_json)}));}
export async function saveTimeline(c,tid,b,timelineId=null){await tenantAuth(c,tid,'timelines:write','editor');const spec=b.spec;if(!spec||!Array.isArray(spec.clips)||!spec.clips.length||spec.clips.length>30)fail(400,'INVALID_TIMELINE','Use 1–30 clips.');const clips=[];let total=0;for(const x of spec.clips){const v=await requireVideo(c,x.videoId,'videos:read','viewer');if(v.tenant_id!==tid||!['mp4','webm','mov'].includes(v.kind)&&v.source_path.endsWith('.m3u8'))fail(400,'EDITABLE_SOURCE_REQUIRED');const start=number(x.start??0,'start',0,86400),end=number(x.end,'end',start+0.05,86400);if(v.duration_seconds&&end>v.duration_seconds+0.1)fail(400,'CLIP_OUT_OF_BOUNDS');total+=end-start;clips.push({videoId:v.id,start,end});}if(total>3600)fail(400,'TIMELINE_TOO_LONG');
 const overlays=[];for(const x of spec.textOverlays||[]){if(overlays.length>=20)fail(400,'TOO_MANY_OVERLAYS');overlays.push({text:text(x.text,'text',300),start:number(x.start,'start',0,total),end:number(x.end,'end',0,total),position:['top','center','bottom'].includes(x.position)?x.position:'bottom'});}if(overlays.some(x=>x.end<=x.start))fail(400,'INVALID_OVERLAY_RANGE');
 const normalized={clips,textOverlays:overlays,width:integer(spec.width??1280,'width',320,1920),height:integer(spec.height??720,'height',240,1920),fit:spec.fit==='crop'?'crop':'contain',fade:spec.fade===true,encrypted:spec.encrypted!==false};if(normalized.width%2||normalized.height%2)fail(400,'DIMENSIONS_MUST_BE_EVEN');const name=text(b.name,'name',160),id=timelineId||uid('tl_');const old=timelineId?await c.db.one('SELECT * FROM timelines WHERE id=? AND tenant_id=?',[id,tid]):null;if(timelineId&&!old)fail(404,'TIMELINE_NOT_FOUND');if(old){if(agentOnly(c)&&old.agent_id!==c.actor.agentId)fail(403,'TIMELINE_OWNER_REQUIRED');await checkRevision(c,old,b.expectedRevision);}await c.db.batch([...policyOps(c),...(old?revisionOps(c,'timelines',old,b.expectedRevision):[]),['INSERT INTO timelines(id,tenant_id,name,spec_json,created_at,updated_at,agent_id) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,spec_json=excluded.spec_json,revision=timelines.revision+1,updated_at=excluded.updated_at',[id,tid,name,JSON.stringify(normalized),now(),now(),agentOnly(c)?c.actor.agentId:null]]]);await c.db.audit(tid,c.actor.email,'timeline.save',id,{clipCount:clips.length});return {id,name,spec:normalized,revision:(old?.revision??0)+1,durationSeconds:total};}
export async function eventSettings(c,tid){await tenantAuth(c,tid,'videos:read','viewer');if(agentOnly(c)){const af=videoFilter(c);return {detections:await c.db.all(`SELECT d.* FROM detections d JOIN videos v ON v.id=d.video_id WHERE d.tenant_id=? AND ${af.sql} ORDER BY d.created_at DESC LIMIT 100`,[tid,...af.args])};}return {rules:await c.db.all('SELECT * FROM detector_rules WHERE tenant_id=?',[tid]),detections:await c.db.all('SELECT d.*,r.name FROM detections d JOIN detector_rules r ON r.id=d.rule_id WHERE d.tenant_id=? ORDER BY d.created_at DESC LIMIT 100',[tid]),webhooks:await c.db.all('SELECT id,url,enabled,created_at FROM webhooks WHERE tenant_id=?',[tid]),deliveries:await c.db.all('SELECT id,event_id,state,attempts,last_status,created_at FROM webhook_deliveries WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',[tid])};}
export async function saveRule(c,tid,b){await tenantAuth(c,tid,'events:write','editor');const id=b.id||uid('rule_');if(b.id&&!await c.db.one('SELECT id FROM detector_rules WHERE id=? AND tenant_id=?',[id,tid]))fail(404,'RULE_NOT_FOUND');if(b.matchMode&&b.matchMode!=='keyword')fail(400,'KEYWORD_RULES_ONLY','These rules match indexed text, not raw live video or a safety-certified detector.');await c.db.run('INSERT INTO detector_rules(id,tenant_id,name,query,enabled,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,query=excluded.query,enabled=excluded.enabled',[id,tid,text(b.name,'name',160),text(b.query,'query',1000),b.enabled===false?0:1,now()]);await c.db.audit(tid,c.actor.email,'rule.save',id);return {id};}
export async function addWebhook(c,tid,b){await tenantAuth(c,tid,'events:write','admin');const topics=b.topics??['video.detection'];if(!Array.isArray(topics)||!topics.length||topics.length>2||topics.some(x=>!['video.detection','video.job'].includes(x)))fail(400,'INVALID_WEBHOOK_TOPICS');const url=allowedExternal(b.url,c.env,'WEBHOOK_HOSTS').href,id=uid('wh_'),secret=randomToken();await c.db.run('INSERT INTO webhooks(id,tenant_id,url,secret_ciphertext,created_at,topics_json) VALUES(?,?,?,?,?,?)',[id,tid,url,await seal(secret,c.env.ENCRYPTION_SECRET||c.env.SIGNING_SECRET),now(),JSON.stringify([...new Set(topics)])]);await c.db.audit(tid,c.actor.email,'webhook.create',id);return {id,url,secret,signature:'HMAC-SHA256 of timestamp + "." + exact request bytes. Header X-VideoAgentVault-Signature: t=unixSeconds,v1=hex'};}
export async function disableWebhook(c,tid,wid){await tenantAuth(c,tid,'events:write','admin');await c.db.run('UPDATE webhooks SET enabled=0 WHERE id=? AND tenant_id=?',[wid,tid]);return {disabled:true};}
export async function deliverWebhooks(c){const rows=await c.db.all("SELECT d.*,w.url,w.secret_ciphertext FROM webhook_deliveries d JOIN webhooks w ON w.id=d.webhook_id WHERE d.state='queued' AND d.next_run_at<=? AND w.enabled=1 LIMIT 10",[now()]);for(const d of rows){let status=0;try{allowedExternal(d.url,c.env,'WEBHOOK_HOSTS');const secret=await unseal(d.secret_ciphertext,c.env.ENCRYPTION_SECRET||c.env.SIGNING_SECRET),ts=Math.floor(now()/1000),key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(`${ts}.${d.payload_json}`))),signature=[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');const r=await fetch(d.url,{method:'POST',body:d.payload_json,headers:{'Content-Type':'application/json','X-VideoAgentVault-Event':d.event_id,'X-VideoAgentVault-Signature':`t=${ts},v1=${signature}`},redirect:'manual',signal:AbortSignal.timeout(10000)});status=r.status;await r.body?.cancel();}catch{/* No source URL or credential logging. */}const attempts=d.attempts+1;await c.db.run('UPDATE webhook_deliveries SET state=?,attempts=?,last_status=?,next_run_at=? WHERE id=?',[status>=200&&status<300?'delivered':attempts>=8?'failed':'queued',attempts,status,now()+Math.min(3600000,2**attempts*15000),d.id]);}}
export async function sourceList(c,tid){await tenantAuth(c,tid,'videos:read','viewer');if(agentOnly(c))return []; return c.db.all('SELECT id,tenant_id,folder_id,name,kind,created_at FROM sources WHERE tenant_id=? ORDER BY created_at DESC',[tid]);}
export async function addSource(c,tid,b){await tenantAuth(c,tid,'sources:write','admin');const url=allowedExternal(b.url,c.env);if(url.protocol!=='https:')fail(400,'HTTPS_INGEST_ONLY','Raw RTSP/RTMP adapters are not shipped. Use bounded HTTPS ingestion or browser camera/screen recording.');const folder=await verifyFolder(c,tid,b.folderId??null),id=uid('src_');if(url.username||url.password)fail(400,'CREDENTIAL_URL_NOT_SUPPORTED','Use a host-issued, short-lived URL without embedded username/password.');await c.db.run('INSERT INTO sources(id,tenant_id,folder_id,name,url_ciphertext,kind,created_at) VALUES(?,?,?,?,?,?,?)',[id,tid,folder,text(b.name,'name',160),await seal(url.href,c.env.ENCRYPTION_SECRET||c.env.SIGNING_SECRET),url.protocol.startsWith('rtsp')?'camera':'url',now()]);await c.db.audit(tid,c.actor.email,'source.create',id,{host:url.hostname});return {id};}
